### ISSUE TITLE
Cannot change a node symbol with non-svg symbol

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#1017]
[1.4.1/Linux]
Using a non-standard non-svg symbol for templates works fine and that's great.
However, changing a node symbol by right-clicking " change symbol" and choosing a symbol added in the "symbols" folder leads to the following error:
![issue changing symbol](https://cloud.githubusercontent.com/assets/13176858/12922533/2b0d4b1e-cf52-11e5-9e98-4962bfdbab2c.jpg)
Is this behavior expected?

**Comment by noplay** [comment]
It's a known limitation. Since the node object for SVG and Bitmap is different in Qt.

Perhaps a way to fixed it is to stop using PixmapImageItem for the node in topology. In case of of a bitmap image we can convert it to a SVG with the embed as base64 at display. This should be transparent for user and the image are small should not be slower.

Sample SVG with image embed (found on internet no idea of the result :P):
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<image width="20" height="20" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="/>
</svg>
```


What do you think @grossmj ?

**Comment by grossmj** [comment]
We could give it a try.

@jean-christophe-manciot  In the meantime, make sure you change the symbol directly on your template in the preferences since the decision to use a Pixmap vs a SVG object is made when you drag & drop a node on the scene.

**Comment by jean-christophe-manciot** [comment]
It's already done.
But one object may take different types of symbol over time.

**Comment by jean-christophe-manciot** [comment]
Also, unless I missed something, it does not seem possible within GNS3 GUI to change the symbols of default nodes templates, such as the host for instance.

**Comment by grossmj** [comment]
You are correct, cloud and host are built-in.

**Comment by noplay** [comment]
For the cloud and host I think we will fix that the day where we will refactor the cloud object: #867 and https://github.com/GNS3/gns3-server/issues/402

**Comment by noplay** [comment]
I pushed a PR for this.
