### ISSUE TITLE
REQ - Duplicate a device (including Config)

### ISSUE THREAD

**Issue by uktricky** [GNS3/gns3-gui#1065]
Within GNS3 be able to right click on a device and select duplicate (like we do for text boxes etc) would force the name of the device to change but would copy the device and config.  Obviously we'd need to amend config once the device was started as required.

Even better would be to highlight an area of Topology in GNS3 and be able to "Copy" and then "Paste" either into existing or New Project?

**Comment by noplay** [comment]
https://gns3.com/qa/feature-request-the-ability-to-c

**Comment by grossmj** [comment]
I think the duplication should be done on GUI side... what do you think @noplay?

**Comment by noplay** [comment]
I think it's not easy and could only be done on server side because require direct access to the disk.

And each emulator need a specific implementation. By the way duplicate for text & co will also need to be backported for 2.0 when this elements will be server side.

# Dynamips
* copy the config files
* fix the name in the config

# VPCS
* copy the config files
* fix the name in the config

# IOU
* copy the config files
* fix the name in the config

# Qemu
* copy the disk
* change the mac address

# Docker
* copy the files

# VirtualBox / VMware
* create a linked clone or copy the vm or disallow?

**Comment by noplay** [comment]
Note for some appliance duplicate will create a trouble because crypto key like the ssh fingerprint will be the same.

**Comment by grossmj** [comment]
I think we can have a warning about that so users are aware of it.

**Comment by noplay** [comment]
Current status:

* [ ] IOU
* [x] Dynamips router
* [ ] Docker
* [x] VPCS
* [ ] VMware
* [x] Ethernet switch
* [ ] Atm switch
* [ ] Frame relay
* [ ] VirtualBox
* [ ] Qemu

**Comment by noplay** [comment]
For VMware and VirtualBox we can't support duplicate because without linked clone it's not possible.
