### ISSUE TITLE
Imported appliance with ova image can be used only as a linked base VM

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1112]
GNS3 version 1.4.4 on Linux (64-bit) with Python 3.4.2 Qt 5.3.2.

When an appliance with an ova image is imported, the containing vmdk disk images are stored unchanged in the GNS3/images/QEMU directory. These are normally compressed/streamOptimized images. They are fine as a base of a linked base VM, but they can't be used as a normal (non-linked) image.

If you try, you get the following error message:

```
Error: QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-i386 -name 'NETem 0.0' -m 128M -smp cpus=1 -enable-kvm -boot order=c -drive file=/home/behlers/GNS3/images/QEMU/NETem.ova/NETem-disk1.vmdk,if=ide,index=0,media=disk -serial telnet:0.0.0.0:2001,server,nowait -monitor tcp:127.0.0.1:56642,server,nowait -net none -device e1000,mac=00:00:ab:99:03:00 -device e1000,mac=00:00:ab:99:03:01 -nographic

Execution log:
qemu-system-i386: -drive file=/home/behlers/GNS3/images/QEMU/NETem.ova/NETem-disk1.vmdk,if=ide,index=0,media=disk: could not open disk image /home/behlers/GNS3/images/QEMU/NETem.ova/NETem-disk1.vmdk: VMDK version 3 must be read only
```

I see three possibilities:
- As non-linked base VMs are an exception in QEMU, define this behaviour as a restriction
- Provide a convert function in the HDD tab of the qemu VM configuration wizard, very similar to the existing "Create..." function. It allows to make a qcow2 image out of the vmdk image.
- Make that conversion the default during import of an appliance.

**Comment by noplay** [comment]
For the moment I don't have a good solution.

My opinion on the three possibilities:

> As non-linked base VMs are an exception in QEMU, define this behaviour as a restriction

Not a big fan of that. Because it's magic for the user. Some file work and some not.

> Provide a convert function in the HDD tab of the qemu VM configuration wizard, very similar to the existing "Create..." function. It allows to make a qcow2 image out of the vmdk image.

Current Qemu options are too complex for me. The create image is very very rarely used. 

> Make that conversion the default during import of an appliance.

The best solution. But probably need ground work before.

Actually this mean using the qemu-img on the OS where is import is made. It will not work for OSX because we can not provide a cross OSX version of qemu 2.X. And we are not really confident with windows version. Ideally the GUI should stop manipulating the file and just send them to the remote server where the conversion could be done. The conversion itself is a risk because for large image (it's common to have VMDK of 10GB) we have a high risk for the user to be out of free disk space.

Another problem after conversion the hashsum will change. We can no longer recognize the image.

**Comment by ehlers** [comment]
The qemu-img command to convert is simple: `qemu-img convert -O qcow2 input-image output-image`. At least this has always worked for me.

Converting on the GUI system is problematic. For the compressed VMDK at least qemu 1.2 is needed (according the changelog, I use only v2.x). So qemu-img on OSX and Windows won't work.

**Comment by ehlers** [comment]
I agree, that converting at the server is critical, as we don't know if it has enough free space.

On the GUI we don't have to use qemu-img. Qemu works well with uncompressed VMDK disk images, only the compressed/streamOptimized images can't be used as a RW media. So we can also use the VMware or VirtualBox tools:
`vmware-vdiskmanager -r compressed.vmdk -t 0 uncompressed.vmdk`
or
`VBoxManage clonemedium compressed.vmdk uncompressed.vmdk --format VMDK`

As the GUI will likely use the GNS3 VM, in most (but not all) cases we can use those tools.

Another question: Why is it not possible to create a cross OS X version of qemu-img v2.5 ? I just compiled a brew version of qemu-img v2.5 on my El Capitan OSX and managed to link the brew libraries statically into the qemu-img binary. So it needs only the system libraries. I verified it by uninstalling the brew packages, my qemu-img is still working.

**Comment by noplay** [comment]
The problem is getting this binary to work with older version of of OSX.
In previous tests we got bad surprise with this. Perhaps for qemu-img it's
not an issue.

**Comment by noplay** [comment]
What fo you think about this @grossmj ? I don't think we have an easy fix for the moment.

I'm not confortable to add it to the GUI because it's adding more complexity to the GUI code when we try to remove it, and it will not work for web interface.

We can convert it at the first launch but we can not reflect the change on the client template and we will need to manage the errors during the conversion process and manage the case where you start two qemu.

We can convert it at upload, but how to manage the case of linux where we don't upload stuff?


The more we support OVA, the more we got trouble :( Perhaps we need a dedicated ova import. 

=> File / Import OVA 
=> You select a server
=> The file is uploaded 
=> The file is converted and from the OVA info a device is created (easier in GNS3 2.X since the controller will control everything)

**Comment by grossmj** [comment]
Makes a lot more sense to do it in 2.x because it will be a lot easier and clean.

**Comment by ehlers** [comment]
OVA support has been dropped in v2.0, commit https://github.com/GNS3/gns3-gui/commit/0a3697962b342740e79d087db4791810a61218e2.
