### ISSUE TITLE
Drop converter from old version in 2.0?

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1147]
# IOU VM converter
This is not tested with recent version and I suppose not really used. And with 1.5 we shipped a way to fix topology in order to use the new server.  We will have ship two major version in the interval.

I think it safe to remove it.

# Support for old .net topologies

It's harder to drop. We will probably keep it. But since it's a new big release it the occasion need to be ask. And in the web interface we will probably not adding this. It's not uncommon for software to say the migration is only supported from a big release to another (for example MySQL upgrade from 5.0 to 5.5 require the use of 5.1 before).

## The con
Arguments against keeping it:
* people are not testing it if we break it with all architecture change we will not see it
* the converter is not maintain by his author and we lost contact with him
* if the converter failed in early version people think the converter is not working and have not try since
* 1.X is really stable, if people are conservative and using 0.8.7 they could migrate to this really stable version 
* we can expect to have a location in the community with user topologies working with recent version
* you can still use it via command line
* the missing parts will never be fixed

## The pro
* some people still using 0.8.7
* you can find this topologies on internet
* it's work for the moment

An intermediate solution could be to mark this feature End Of Life in the release note of 1.5 and encourage people to migrate topologies to the 1.X format. And we could drop it if need in the future.

**Comment by grossmj** [comment]
I am for dropping it.

**Comment by grossmj** [comment]
or show a warning when someone try to open a .net file saying this is not supported etc.

**Comment by danieldemers** [comment]
Do not spend time on making sure the converter will work in 2.0. At some point you need to move forward. The community needs to focus on innovating, not dragging the past with you at the cost of valuable cycles. The GNS3 team is small and development time to release is slower because of this. 1.4 is very stable and is a suitable place for converted projects to reside. 

If the converter is important enough the community members will create a process to bring it to 2.0. The GNS3 team IMO needs to focus on the core dev.

**Comment by grossmj** [comment]
Good points. Let's drop it.
