### ISSUE TITLE
1.5: Console port often conflicts with docker aux port

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1154]
GNS3 version 1.5.0dev1 on Darwin (64-bit) with Python 3.5.1 Qt 5.6.0.

When using docker container together with other VMs, in this case dynamips, very often I get these warnings, when I load the project:
`Warning: TCP port 5001 already in use on host 0.0.0.0. Port has been replaced by 5005`

Everything is working fine, so it's not a problem. But it's irritating.

The topology looks like that:
![mcast](https://cloud.githubusercontent.com/assets/896406/14232020/269d1916-f99a-11e5-8a5c-ece9986151da.png)

Port 5001 is normally the console port of R2, which is taken by the AUX port of tools-2.

My current theory what's happening:

In the project file for the docker container the AUX port is not reserved, so it's allocated dynamically. It often happens, that it allocates a port that is reserved by a console of another device. When this device wants it's console port, it sees that it is already in use and chooses another one. That results in this warning.

So I suggest to save the aux port of the docker container also the topology.

Another more radical way would be to make the port allocation dynamic for all devices. A user, who has a scripts, that wants to interact with a device could use the custom console feature. But perhaps that's more an idea for 2.0.

**Comment by noplay** [comment]
The simple is to save the aux port and restore it.

I think should we take advantage of the 2.0 to remove port assignation. Since it's not compatible with multiple projects opened at the same time. Also it could simplify stuff if like VIRL in a later version we have all telnet communication forwarded by a central point (the controller could use the port 2001 and forward to a console on 3004 which port the user will controlled?).

The use case for port assignation actually is people expose GNS3 topology without the GUI. But if in 2.0 we have a basic web interface with a list of the VM of a project and a link to open a console it's work (it's already the case in my dirty test interface).

Also this open another point. Since we have change the port range, a lot of user will see the warning when using an old topologies in 1.5.

**Comment by ehlers** [comment]
What about a one-time warning on first run of 1.5, that the console port ranges have been changed and all external scripts have to be adapted. If anyone would read the changelog, it would be enough to mention it there.

Additional remove that warning, I assume it will mostly create irritations.

**Comment by noplay** [comment]
If you are not using the GUI you will not see the warning. This mean the user that really need the warning can not see it.

I'm for dropping the warning since it's annoying when you open two projects.

**Comment by noplay** [comment]
Also actually the warning will be show if you import a topology from someone using a different port ranger.
