### ISSUE TITLE
REQ : name of network card of Host device

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1229]
Hi

Is it really necessary to show name "nio_gen_eth:eth0" and "nio_tap:tap0" with the networks cards of Host device ?

Can we have a name more understandable as "real:eth0" (real:tap0) or "host:eth0" (host:tap0) or other ?

(sorry if it is already do on next gns3)

**Comment by grossmj** [comment]
This is going to be part of https://github.com/GNS3/gns3-gui/issues/1116

**Comment by Raizo62** [comment]
I don't know. For me, the cloud is useful to do special thing that are not "include" by devices of GNS3.
Host device is useful to connect easily the virtual network to the real world.
It is not the same thing (even if it's the same code behind). Then i think that clarify the names of interfaces of Host device is a good idea. But it will not be a good idea on Cloud.

**Comment by noplay** [comment]
I think for most people only eth0 or tap0 make sense as name they don't care about the details on how GNS3 inject packet inside.

**Comment by Raizo62** [comment]
> I think for most people only eth0 or tap0 make sense as name they don't care about the details on how GNS3 inject packet inside.
i think too (for Host Device)

**Comment by grossmj** [comment]
@Raizo62 we will probably drop the host device in 2.0 because it confuses users. Maybe we can have the cloud object behave like the host one?

**Comment by grossmj** [comment]
The host object could be replaced by https://github.com/GNS3/gns3-gui/issues/867 if an user really wants it.

**Comment by grossmj** [comment]
The cloud object now uses the network interface names directly (no more "nio_gen_eth:eth0" or "nio_tap:tap0").

**Comment by Raizo62** [comment]
> The host object could be replaced by #867 **if an user really wants it.**

Host object is not useless : when you have a server on VM without graphical interface , and you want to connect it with GUI (for example : webserver and browser) 

I will look after #867

**Comment by noplay** [comment]
You can do that with the cloud the limitation is by default the cloud has no interface when host as all interfaces added by default.

#867 will allow you to create a template with interfaces added to a cloud 

We think this will drop a huge source of confusion for most people because they were not really different.

**Comment by Raizo62** [comment]
> #867 will allow you to create a template with interfaces added to a cloud

Will I must add all interface manually or is it doing automatically ?
I don't always know the number of interfaces and their names (example : Live Raizo)

**Comment by grossmj** [comment]
I think we will automatically add the interfaces.

**Comment by noplay** [comment]
Not sure the template system requirements is to be able to save a set of interface as a node you can use in the applications. Adding a an auto add system mean bringing back the host node with current issues.

Personally if we really want this I prefer to have a builtin host node instead of a template with a checkbox for auto add all interfaces. But I will filter the list to keep only real interface in the host like what I suggest in #1279 otherwise if you have vmware host node is almost unusable.

**Comment by Raizo62** [comment]
> Personally if we really want this I prefer to have a builtin host node instead of a template with a checkbox for auto add all interfaces. But I will filter the list to keep only real interface in the host like what I suggest in #1279 otherwise if you have vmware host node is almost unusable.

Yes, it is also an good idea.
(Remove also the interfaces created for docker.)

I have an another example of use : Your host is connected to Internet only with Wifi. You want connect your virtual network to internet. You must use your host as router.

**Comment by grossmj** [comment]
I've implemented it already and it filters all "special" interfaces (vmnets, vboxnets, docker, lxc, openvswitch).
