### ISSUE TITLE
Config is lost if you change the IOS images

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1233]
https://gns3.com/qa/gns3-has-problem-with-opening-pr

**Comment by noplay** [comment]
Not tested

**Comment by grossmj** [comment]
Problem is more important than I thought, basically any update to an existing IOS node (via the Node properties dialog) will reset the startup-config file to almost nothing.

Bug is due to this commit https://github.com/GNS3/gns3-server/commit/2938b97bd468cdb1f4f6c6062fca68800fcfb119

@noplay I blame you, I blame you, I curse you! ;)

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/67e346ba92e9206c6770b9d4a987cd02aa596859
