### ISSUE TITLE
REQ : to import the functionalities of remote servers

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1278]
Hi

When we connect the gns3-gui to a remote server, we must configure our gns3-gui with all devices known by remote server.

Can we have an import button who imports all the "Devices" (name, config, idle,...)  known by remote server ?

Remote gns3-server could use the config into gns3_gui.conf beside him

**Comment by noplay** [comment]
This the big work for 2.1. Actually the information is not located on the remote server.

**Comment by Raizo62** [comment]
The remote gns3_server can read config into the remote gns3_gui.conf if  gns3_server can found this file.
(But yes, it is perhaps a big work)

**Comment by noplay** [comment]
Not in every scenario it's only when have the GUI and server running on the same host.

The plan with 2.0 is to move to a notion of controller the controller will be a central server managing all the GNS3 server (it's mostly transparent for user your local server by default is your controller). This controller will know everything about your topologies. 

We delayed to a 2.1 the move of the Devices to the controller because otherwise it will be a too long tunnel without releases. But it's the vision.

**Comment by noplay** [comment]
We have embed something in 2.0
