### ISSUE TITLE
[2.0] Filter vbox and vmnet interface from the cloud object

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1279]
Actually the list of interface could be very long in the cloud node:
![image](https://cloud.githubusercontent.com/assets/345437/15702082/3a6f8ee8-27de-11e6-8e01-529de41b0080.png)

My proposal is too filter from this list vbox and vmnet and to put them in dedicated tabs with a warning message about the existence of a native support:
![image](https://cloud.githubusercontent.com/assets/345437/15702153/bcf5c06c-27de-11e6-8b98-9d1a08b675ac.png)

This tab could also be a checkbox allowing to filter "special interface". I this case we could blacklist more interface like fw0 (firewire on mac), docker0.

**Comment by grossmj** [comment]
Well, you can already filter if you right click in the list. However, I am not satisfied with that because it is easy to miss it. A checkbox is problably a better idea. I don't want a VMware interfaces tab because there are also Docker, LXC, Openvswitch and VIrtualBox interfaces that I want to filter too.
