### ISSUE TITLE
Rename IOU implementation to IOL

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1298]
For consistency with other projects like Unetlab and VIRL we should also use the IOL (IOS on LInux) name instead of IOU (IOS on UNIX).

**Comment by noplay** [comment]
Perhaps we should wait the release of IOL for VIRL.

Because it's possible that the support for IOL from VIRL will be totally different of current IOU. And we will need to avoid confusion when using it.

**Comment by grossmj** [comment]
Indeed, this can wait.

**Comment by gcasella** [comment]
From what I know with IOL from VIRL is that it would run in an LXC Container -- I'm not sure how it would work in terms of GNS3 supporting Docker (Don't have too much experience with LXC)

I'm sure like any of the other images on Cisco VIRL you would be able to export them to use within GNS3.

**Comment by taurus8** [comment]
How about old IOL/IOU images ?
will old images be supported ?

**Comment by taurus8** [comment]
In Updated section from this https://learningnetwork.cisco.com/docs/DOC-30952

"there is no 'serial console' present on the IOL instance. A maximum of 16 Ethernet interfaces are provided."

but old IOU images supports serial interfaces

**Comment by noplay** [comment]
Until we can't test we can't know what we will do.

I'm pretty sure we will keep the current IOU support for the moment and have a different way to load IOL (if we are lucky could be a part of the docker support).

A tricky part will be to avoid confusion between the old IOU and the new IOL.

After that we will need  to have reflexion because current IOU images work with specific version of libs, a system upgrade could broke them one day. If ubuntu stop 32 bit support we will need to find solutions.

**Comment by noplay** [comment]
VIRL has announced that they have no release date for IOL due to unexpected internal process requirements (translation someone probably block the release inside Cisco).

**Comment by grossmj** [comment]
I think this is unnecessary now.
