### ISSUE TITLE
Add an option to configure the Custom console via the General preferences tab

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#1303]
Add an option to configure the Custom scripts via the General preferences tab
or
Allow the user to open gns3gui.ini from the GUI.

**Comment by noplay** [comment]
I don't get it. You can already configure custom terminal in preferences.

We have an options to locate the preferences in the GUI  in preferences allowing you to locate the preference files. I'm not sure making it too easy to edit the config file by hand is a good idea because it's dangerous, advanced users could already do it.

**Comment by 1001QAdotNET** [comment]
How do I get to that option, where is is located?
For now the only way to edit the custom console (which I use as a proxy for scripts) is to select a device and then use the dialog to add scripts etc.
If you want the software to get richer functionality and to have community contributed scripts and enhancements you have to find a way to give us access to some knobs like the .gns3 file, script hooks etc. I have not investigated the REST APIs yet to see if the above are doable that way but my feeling is that it is not possible.

What are your plans, what is your strategy, in regards to opening GNS3 to used added functionality? Is there a time line for this?

**Comment by noplay** [comment]
You can add your command like this:
![image](https://cloud.githubusercontent.com/assets/345437/16949146/58e58160-4db9-11e6-939f-d2c8651cd715.png)


![image](https://cloud.githubusercontent.com/assets/345437/16949129/3c966ede-4db9-11e6-8e6e-f9f19ef17fd1.png)

**Comment by noplay** [comment]
Is it what you want? 

For the strategy I will be happy to reply but in order to have more visibility by the community and not by just dev could you open a thread on:
https://gns3.com/community

In short:
REST API should we be the way to go and starting with 2.0 enough elements should be exposed to allow this.

**Comment by 1001QAdotNET** [comment]
That is what I was using, apparently that was changed. That edit/save was available when you would select a device, Not anymore. Maybe it was where it is now but I never used that way. Good to know that it will be available only there from now on. 

Re: REST ..sounds good
Re: opening a thread- what title should I use for that topic? Do you want to start a discussion to collect ideas ?

**Comment by noplay** [comment]
The title could what you want want.
"What are your plans to opening GNS3 to user added functionality? "

And your message could be:
"If you want the software to get richer functionality and to have community contributed scripts and enhancements you have to find a way to give us access to some knobs like the .gns3 file, script hooks etc. I have not investigated the REST APIs yet to see if the above are doable that way but my feeling is that it is not possible.

What are your plans, what is your strategy, in regards to opening GNS3 to user added functionality? Is there a time line for this?"

I will reply with our plan, timeline & co so everyone will be able to give feedbacks.
