### ISSUE TITLE
Feature request - notification in console after import/export configs

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1325]
Hi,
it would be really great to see some kind of notification when you import/export config from the folder, like
"Import from ~/whatever/path/is was successful"
"Export to ~/whatever/ was successful".
I was thinking of this, because the following happens quite often to me:
I import configs and immediately switch to some other window, then I just forget if I loaded the correct configs.
Thanks!

**Comment by noplay** [comment]
It's take time for you to import config?

**Comment by dmfigol** [comment]
Nope, it doesn't, I see your point and I can't really explain why I have such a problem in the first place, but I still think it would be beneficial to see what is going in GNS3 console.

**Comment by noplay** [comment]
@grossmj what do you think?

**Comment by cambrant** [comment]
I think explicit notifications when acting on a command from the user is often a good practice. It prevents the user from wondering if their command had any effect at all, and allows the user to look back a couple of steps to make sure, like @dmfigol said.

Of course, the log shouldn't be cluttered, but when adding/removing devices, importing/exporting configs, starting/stopping the server, it generally helps to be more verbose than quiet.

**Comment by noplay** [comment]
For me the visual feedback should be enough otherwise people will not read message in the console. Actually what we do is to display a progress bar if the operation is longer than a few milliseconds.

The problem is more to remember what was your previous operations. This could be like the vsphere interface (look at the bottom). In their case the event log is by VM:
![](http://blogs.vmware.com/vsphere/files/2016/05/2016-03-07_1741_H5client_-_screenshot0.png)

In the web app I was thinking to not display the console and instead showing non blocking alert box like this:
http://getbootstrap.com/components/#alerts-dismissible

We didn't test web UI for the moment. Not sure if it's a good idea. Probably a log tab somewhere could be usefull with low priority info.

**Comment by noplay** [comment]
Replaced by #1334 we need to redesign the whole logging system before adding more information.
