### ISSUE TITLE
Add support to save config files in containers and export them in portable projects

### ISSUE THREAD

**Issue by ddompe** [GNS3/gns3-gui#1359]
This is an enhancement request. I would like to be able to specify certain file on the docker configuration to be saved as the configuration of the container (for example /etc/network/config so that uses the same mount as the interfaces today). In OpenSwitch we can make the configuration of the switch in this file, and allowing the file to be included on portable projects would make it very useful for sharing topologies and examples.

**Comment by noplay** [comment]
Not sure to understand the question. It seem we already support it but probably not clear in the doc:
https://gns3.com/support/docs/docker-2

You want /etc/network/config to be included in portable project? 

All VOLUME directory will be persist on disk. And /etc/network is special because persisted by default.

**Comment by ddompe** [comment]
Ok, from looking at the code indeed looks like is doing what I wanted (even better than I have thought so).

In OpenSwitch the configuration is saved in a separate partition (/var/local) for real hardware, so it seems like by adding the partition as VOLUME I can get it saved locally.

Now my request is that all those partitions are included in the portable projects, that way I can share a project pre-configured.

**Comment by noplay** [comment]
It's already the case :)
