### ISSUE TITLE
qemu and md5sum

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1368]
Hi

I don't know if this is a bug, or if this is necessary.

When I put a qemu device on the topology, gns3 calculates a md5sum of this image file beside it

It is necessary ? It is take time and "I don't see why it is useful."

I indicate it just if this is only "Oups, I forgot to remove it"

**Comment by noplay** [comment]
It's for the future :) It's take time only the first time after that it's cached.

The reasons behind that is
* We plan when you exchange topologies to help you find the missing images on the net or you can even imagine an image server in a school where GNS3 will search for an md5
* On the website when we will allow lab sharing with that we will be able to detect what kind of device is use and add more meta and search options (image name is not reliable).
* Later we could use that to detect if you don't have corrupt the image file. Preventing report from users saying it's no longer work when the reason is they changed the image
* We will probably use that to blacklist/warn when you use image with problems (some version of ASAv for example)

**Comment by Raizo62** [comment]
is it not better to create this md5 when we create the config of this device ? instead of waiting to use this device ?

**Comment by Raizo62** [comment]
is it not better to create this md5 when we create the config of this device ? instead of waiting to use this device ?

**Comment by noplay** [comment]
The config is not managed by the server for the moment. That's why it's only at first need.
