### ISSUE TITLE
unable to close "jungle Newsfeed" box 

### ISSUE THREAD

**Issue by anubisg1** [GNS3/gns3-gui#150]
as per title, you cannot close the news feed. it can only be detached.

![image](https://cloud.githubusercontent.com/assets/4518931/5141321/975d82bc-7174-11e4-9d50-2398f33de6b2.png)

**Comment by elauriault** [comment]
I agree with the original poster. There should be some way to disable this.

**Comment by phocean** [comment]
I financially contributed to the project, so why do I have to suffer from ads ? Does it mean I have to pay 2 times and actually more than users that never contributed ?

It is not fair at all. Whenever possible, I pay all apps because I think work always deserves a salary and I hate ads. So GNS3 is the only app that is showing me ads, and on top of that during my professional activities.
So please reconsider your position, at least for paying users.

**Comment by grossmj** [comment]
@phocean 

I agree, contributors should not see ads. Actually we have started to work on a system to allow crowfunders to deactivate it based on public keys: https://github.com/GNS3/gns3-gui/tree/showdockwidget

However, this is going to take some more releases before we have something ready. The problem we face is we don't really want to police anything nor want to develop a license server or other crazy thing just to enforce who can deactivate ads, we have better things to do.

We may even consider remove it completely or having a "pay what you want" system however for now this is a necessary evil (I don't like ads either) to pay for the development etc.

Finally, are you on Windows or Linux?

**Comment by phocean** [comment]
I am glad to see that you are aware of the issue and it is going to move in the right direction in future releases. 
To answer your question, I am running on Linux (currently Fedora 21).

**Comment by elauriault** [comment]
Also a crowdfunder. I am on Ubuntu 14.10.

Very glad to see you guys addressing this.

**Comment by mapfumo** [comment]
The "jungle Newsfeed" box can be removed by editing gns3_gui.conf. Toggle "hide_news_dock_widget": false to true
