### ISSUE TITLE
[2.0] REQ : cloud and NAT device

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1638]
Hi

NAT device use libvirt.
I have perhaps wrong but libvirt only starts a DHCP server, configures "iptables" and actives routing.
If theses services are already on the real host, it is useless to install libvirt (On LiveRaizo, i look after bytes ;-))

On real host without libvirt or DHCP server, the "NAT device" is useless.

I suggest this : 

- Modify the configuration interface of "cloud node" to works also with bridged interface (as NAT device)
- Change "NAT device" as device add by default in this "cloud node" configuration.

And, for Christmas :-), you add also an button to active or not each configurated device : not needed to delete device

**Comment by noplay** [comment]
Cloud support bridged interface, behind the scene NAT use the cloud.

libvirt create also an interface dedicated to that.

In your case I suggest that we add a configuration settings for changing the name of this interface. So you will be able to choose which interface is the nat interface in LiveRaizo and you are responsible to provide to this interface NAT and DHCP.

Why a nat node instead of using the cloud? Portability if we know that in a topology something is the nat we can associate it to the correct NAT on user host. This mean you should be able to open a topology using NAT on Live raizo with the GNS3 VM.

**Comment by Raizo62** [comment]
Yes, I understand.

But, your "NAT" device is not real NAT : this is your real Host that must be configured as nat-router with libvrt or other.
I prefere a device that is the real Host.
I fear that my students want use Nat device whereas this device do nothing.

**Comment by Raizo62** [comment]
I have tested cloud device : 

- ping doesn't work if i connect vpcs with cloud device with bridge interface
- ping works if i connect vpcs with cloud device with tap interface, but i can use only one device
- ping works if i connect vpcs with nat device, but i can use several nat device.

**Comment by noplay** [comment]
We want to avoid as much as possible the usage of cloud because from our experience it's create too much support and it's complaints number 1. Most of new users want to connect their topologies to the net.

We promote the NAT node, because with libvirt installed it's work out of the box (it's what we do when installed from package our using the GNS3 VM). We will try also to provide a host only node for same easy to use experience.

Actually your students will not be able to use the NAT node if the libvirt is not installed no risk that the node will do nothing.

The cloud is a raw tools we read and inject packets in an interface but after that it's depend of the OS. This make it an expert tools because you need to know what you are doing.

Take for example your bridge, we can inject packet in the interfaces but a bridge is a kind of pipe, you have no idea on which side of the bridge packets will be send.

GNS3 can't know the interface behavior because from our point of view (the userland) an interface is an interface. In 2.0 by default we filter some special interfaces pattern name to limit issues.

**Comment by Raizo62** [comment]
I don't like also Cloud (too big)

I would like to 2 devices : 

- a special device to connect to real host (it uses bridge or tap. now i prefer bridge)
- a special device to connect to real interface (only eth0, eth1...). (a port image?)

But Cloud can be usefull

I think config of cloud will must also configure our own bridge : this device will work as nat device (create interface gns3nat...). Because, if i do not wrong, ping doesn't work (cf previous post)

I will remove nat device because nat device is not nat device if livbirt (or fast-nat on raizo) is not started. And students will want use it even it doesn't work because it seems more easy. The error message will stop them.
User will can use real host device and rename it to nat. This will show to configure dhcp, nat and routing on real computer.

I doesn't like gratuitous IP address on others interfaces (as virbr0 or docker0) : now my students don't think IP address. After if they see others IP, they will never think IP

**Comment by noplay** [comment]
> I would like to 2 devices :
> * a special device to connect to real host (it uses bridge or tap. now i prefer bridge)

I think it's the discussion here: https://github.com/GNS3/gns3-gui/issues/1625

> * a special device to connect to real interface (only eth0, eth1...). (a port image?)

It will remain the cloud. Because we can't change the history. A real interface in GNS3 is the cloud and other software work like that because of us.

For breaking libvirt nat interface you need to modify the configuration yourself.

We will not remove NAT device because it's simplify the life of users. It's a recurring feedback we got from schools, users, manufacturers. We want to have one click internet connection independent of the OS configuration.

I see your point about the need learn DHCP, NAT on the host OS. But often we see school who want to teach router X before teaching NAT on host OS, but they need internet connection for a licence check or something else.

**Comment by Raizo62** [comment]
I know that often, configure DHCP/NAT must be easy. With Live Raizo, commands for DHCP/iptable are already writing for that.
But it is perhaps more complicated on Windows or other OS

I fear that default ip configured on device can have conflict with real/virtual network.

I am sorry that "fake" nat device exists even if libvirt is not installed. But i will do with ;-)

**Comment by noplay** [comment]
Thanks for feedbacks

**Comment by Raizo62** [comment]
Sorry, i am back ;-)

> Why a nat node instead of using the cloud? Portability if we know that in a topology something is the nat we can associate it to the correct NAT on user host. This mean you should be able to open a topology using NAT on Live raizo with the GNS3 VM.

I have tested : it doesn't work. 

- I create a project with vpcs and nat device (with virbr0).
- I close GNS3
- I remove virbr0 (I simule that i send my project to user who doesn't have libvirt)
- I open this project. After the error message, the project is empty.

> But often we see school who want to teach router X before teaching NAT on host OS, but they need internet connection for a licence check or something else.

The best solution is to have a VM with nat/DHCP/router, or to have an IOS with default config who does the same thing.
When i have created "fast-nat" on Live Raizo, it is only to connect virtual network with real world using wifi interface (i didn't found another easy solution)
(Edit : I ask me if your problem is not with Windows : not easy to use real interface ?)

I have tried to configure my own cloud device with bridge interface. I used tab "Ethernet Interface". But i can't communicate with it. To work, i think that GNS3 must configure this device as your nat device (to create gns3nat, to add it to virbr0...). I think you must do a special case with bridged interface in the configuration interface of Cloud

I have understand that you want your nat device, then, can i have a button to hide your nat device in the list of devices ? please ? :-D 
Because i like your bridge device virbr0 if his configuration works, and if i used it, your nat device doesn't say error message but doesn't do nat by default. If i use an another name for virbr0, i will have a very attractive but useless button....

**Comment by noplay** [comment]
When I remove libvirt and open a project using it:
![capture d ecran 2016-11-02 a 13 41 48](https://cloud.githubusercontent.com/assets/345437/19929143/39820342-a102-11e6-8d20-da9294eaf0db.png)

![capture d ecran 2016-11-02 a 13 42 16](https://cloud.githubusercontent.com/assets/345437/19929146/3ccd04e8-a102-11e6-9f8c-6a2e8a68600a.png)

It's the expected behavior in 2.0, unlike 1.X if your machine don't have all requirements you can't open a project in order to avoid corrupting it.

The problem is even on Linux depending of your settings is not necessary easy to setup, if you need to deal with stuff like network manager.

I don't know if we can do something about bridge. From our point of view it's an interface we don't know if it's a bridge or a real ethernet card.

Actually you can not give a topology to someone else that need to connect to the internet because host interfaces are different on each computers and across OS. If you don't enable it you break topology portability. And for us this is very important. What we say is "if you use a linux box or the GNS3 VM you can open any topologies using the .gns3project format"

Perhaps one day probably we can drop libvirt and do our own nat, but for the moment it's solution working on any Linux distribution without effort for user.

**Comment by Raizo62** [comment]
> [ your test ]

I have same messages.
I have tested a project without libvirt because I believed that you want to use "nat device" as indicator which says "here, you must have NAT".

> I don't know if we can do something about bridge. From our point of view it's an interface we don't know if it's a bridge or a real ethernet card.

User can know if this is bridge.
If i have not wrong, device created with the "Ethernet Interface" does not work with bridge interface.
If you add a special tab for bridge interface, you can use the same code for nat device and this device works also.
But, yes, newbies users can create devices that do not work (use bridge interface with ethernet device, or ethernet interface with bridge device)

**Comment by Raizo62** [comment]
> Actually you can not give a topology to someone else that need to connect to the internet because host interfaces are different on each computers and across OS. If you don't enable it you break topology portability. And for us this is very important. What we say is "if you use a linux box or the GNS3 VM you can open any topologies using the .gns3project format"

An idea to give topology to someone else : To create an interface named "error" on Cloud device (more exactly an table of interfaces). User can not use these interfaces. When GNS3 want connect cable on an unexistent interface, it connect the cable to this error interface. When user remove this cable, this interface disappears. When we look description of this error interface, we see the name of original interface.
So user can modify the topology to work. I think that is better that to have nothing.

**Comment by noplay** [comment]
I think If we do that some people will complaints on forum saying ping doesn't work. If we don't block them they will just ignore the error and continue and complaints later that things doesn't work creating complex support.

**Comment by Raizo62** [comment]
You could perhaps add an big error symbol on theses devices and/or error message box after loading.
I think it is better to have an incomplet lab that nothing because the creator has used a device (who is perhaps useless in the lab).
if not, you will have always peoples will complaints on forum saying they can't open your lab ;-)

**Comment by noplay** [comment]
You proposal is valid, but has big impact, GNS3 need to be able to manage half working topology without hiccup, properly display errors, allow to correct the status if an external factor change (the interface is now available). We need to be very careful to not doing something that could corrupt user project. 

In current situation at least we will display them the error that they need to fix and they will not be able to corrupt the project.  


It's one of the reason why we want to avoid beginner using cloud, you need to deal with host errors. That why we will ship nat and host only because you can't break a topology. If your nat is not available it's because you didn't configure GNS3 correctly and you can fix it.

**Comment by Raizo62** [comment]
ok, i understand your point of view.
Although I am a bit disappointed: i liked the realism offert by GNS3.

Then the configuration of our own cloud can not use bridge (as do nat device) ?

**Comment by noplay** [comment]
You can see the NAT as an ISP box.

But we are still free to use the cloud. It's the most powerfull tool of GNS3. We try just to offer simpler alternative for common use cases.

Also a point that could interest you about why keeping simple the behavior. With 2.0 we push a clean API allowing third parties interfaces (web, mobile, cli, an interface for teacher...) to control GNS3. If we implement complex error management they will need also to implement it.

I have look again the code of the NAT and I didn't remember but we connect a tap to the bridge:
https://github.com/GNS3/gns3-server/blob/2.0/gns3server/compute/builtin/nodes/nat.py

I will see if detection of interface type is possible (it seem digging in /sys we can get the info I hope it's the case on all linux):
https://github.com/GNS3/gns3-server/issues/761
