### ISSUE TITLE
gns3-gui settings allows for multiple servers, but only one iourc file

### ISSUE THREAD

**Issue by anubisg1** [GNS3/gns3-gui#164]
gns3 gui can connect to one or multiple remote servers.
The "IOS on Unix" settings, allow you to chose 1 iourc file to upload on the server.

problem:
each server will likely require a different iourc file.
Having the chance to push only one iourc will break all but one server

solution:
iourc file is a "server related setting" . The setting for pushing the iourc file should be moved from "general" settings into "server settings" and allow each and every server to be configured with its own iourc file

**Comment by AdrianSimionov** [comment]
You can have only one IOURC file, even if it is used by multiple servers. The way to do it is:

[license]
Home-PC = cfa46e80131f2e4b;
Work-PC = a3df49864837569d;

**Comment by grossmj** [comment]
Hi,

As Adrian said you can add multiple servers in your iourc file. However, I have just implemented a way to use an iourc file on server side instead of the one configured in the GUI.

All you have to do is create a server.conf file in ~/.config/GNS3 and add the following content:

```
[IOU]
iourc=<path_to_iourc_file>
```

This should do want you want to achieve.

Related commit: https://github.com/GNS3/gns3-gui/commit/e8b2f952af6628c1e6c1232fc832d34627544d28
