### ISSUE TITLE
Qemu headless mode

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1686]
Hi

I use rarely qemu then my idea is perhaps fool

In config of qemu VM, we have the option "-nographic".

Why don't you add a check box as VirtualBox config (Start VM in headless mode) ? If we enable it, you add automaticaly this option ("-nographic").
Then, if i will remove it, i will not need to save the word before in case of i need back

**Comment by noplay** [comment]
@grossmj I don't remember why we don't have headless mode, but something smart detecting if it's possible

**Comment by grossmj** [comment]
I remember that the nographic option doesn't work quite the same on Windows
vs Linux/OSX. Apart from that I am not against an headless mode.

**Comment by noplay** [comment]
I remember if you don't put a -nographic and no X server is running the vm will not start.

**Comment by Raizo62** [comment]
My idea is more to hide the text option behind a checkbox than add/remove this option.

**Comment by noplay** [comment]
After checking more current behavior, not sure that we need to change.

By default we always append -nographic to the options (from the wizard and from gns3a). If you really want to display qemu you can do it by removing it from the option.

I don't see good reason for making it more easy to change because with the VNC support you have a way to display the graphical output and it's work with remote client. And advanced users can play with the option (it's in the advanced settings tab)

For VMware and VirtualBox be able to turn off headless is usefull because you don't have the VNC support and they can display error popup on screen (when qemu will write on stderr).

**Comment by Raizo62** [comment]
> I don't see good reason for making it more easy to change because with the VNC support you have a way to display the graphical output and it's work with remote client. And advanced users can play with the option (it's in the advanced settings tab)

Because, if you remove it, you lose the word "-nographic". If you want set it again, you must search it.

> For VMware and VirtualBox be able to turn off headless is usefull because you don't have the VNC support and they can display error popup on screen (when qemu will write on stderr).

Be careful, VNC support is not the same than headless mode with telnet (on VirtualBox) : with VNC, you can't change the size of the windows as with telnet mode. (Or i didn't success to do it)

**Comment by adosztal** [comment]
The problem is that, in a typical setup, you run the qemu guests on the GNS3 VM (VBox is running on your local computer), which does not have any display server (i.e. xorg) installed. It simply cannot draw the VM's window.

But maybe we're just missing the point; could you describe a use case where this feature would be required?

**Comment by Raizo62** [comment]
I use GNS3 on Linux with local server.

with the appliance linux-tinycore : if i start this VM without -nographic, i have a graphical interface.
If i want start it with console mode, i must reminder to me the word "-nographic"

**Comment by adosztal** [comment]
Just my 2 cents (I'm not a dev), but I think this could break the GNS3 VM if someone disables headless mode for a guest running on the GNS3 VM (which, as discussed, does not have any graphical interface).

**Comment by Raizo62** [comment]
I can't test with GNS3-VM but i suppose that user of GNS3VM can remove the text "--nographic".
A check button could be disabled with GNS3 VM.

**Comment by noplay** [comment]
For TinyCore the GNS3 way to have a the GUI is to setup the console as VNC
instead of telnet. Because it's the method that will work for local
installation and remote. And if you exchange topologies you can't be sure
the other side will run the topology locally or on a computer where Qemu
could use a graphical display.

Because if you disable -nographic and your Qemu is not setup to run with a
GUI it will crash Qemu. For example by default qemu is not compiled with
SDL support on OSX when installed via homebrew.

In the code if no X Server is available in the environnement we force the
-nographic as a security.

On Sat, Dec 10, 2016 at 8:57 AM Raizo62 <notifications@github.com> wrote:

I can't test with GNS3-VM but i suppose that user of GNS3VM can remove the
text "--nographic".
A check button could be disabled with GNS3 VM.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/GNS3/gns3-gui/issues/1686#issuecomment-266188637>, or mute
the thread

**Comment by Raizo62** [comment]
> For TinyCore the GNS3 way to have a the GUI is to setup the console as VNC
instead of telnet. 

Ok, but this VM must have a started VNC server, do not it ? (it is perhaps the case of TinyCore, but other ?)
But i understand your problem.

> In the code if no X Server is available in the environnement we force the
-nographic as a security.

If i have not X server, i can't remove "-nographic" ? 

I think that it will be more easy for you to manage this option with a checkbox that you can disable than a text box that anybody can change....

**Comment by noplay** [comment]
No you don't need to install a VNC server if you edit the qemu you can change console type:
![image](https://cloud.githubusercontent.com/assets/345437/21131736/91898cb2-c110-11e6-942b-f78f423ddf30.png)

This will redirect the qemu display to the VNC client (it's use builtin qemu server).

But it seem it was not obvious for you because it's not in the qemu wizard. It's something we need to improve: #1720

**Comment by Raizo62** [comment]
You are right : i didn't know that.
Thanks.

**Comment by noplay** [comment]
Ok close we will improve the wizard to expose more the VNC feature.
