### ISSUE TITLE
[REQ] Final fix for IOU AMDP2_FE-6-EXCESSCOLL

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#1747]
All L2 IOU images keep giving the bellow error message every few seconds:
`%AMDP2_FE-6-EXCESSCOLL: Ethernet3/3 TDR=0, TRC=0
`

The below which is part of the startupconfig does not help:
`logging discriminator EXCESS severity drops 6 msg-body drops EXCESSCOLL
logging buffered 50000 
logging console discriminator EXCESS
`

The only working solution is to run the below from GNS3 VM shell (before starting any IOU):
`sudo sysctl net.unix.max_dgram_qlen=200000`

Would it be possible to run this command automatically after GNS3 VM starts? #

Thank you,
Sairus

**Comment by grossmj** [comment]
I will investigate this.

**Comment by grossmj** [comment]
Well since this is a command that requires special admin rights, it is not easy to run it from GNS3. We could eventually run it from uBridge which has some privileges (capabilities), either programmatically or by calling sysctl directly but I am not 100% comfortable about the idea of changing system wide params like that.

**Comment by noplay** [comment]
A debate of something similar related to systemd:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762700

I think the only thing we can do on the GNS3 VM is to change is in
 /usr/lib/sysctl.d/50-qlen.conf set net.unix.max_dgram_qlen=512 or a
different value. We can't do it on unknow OS because we don't know if we
will not introduce a side effect and this value could change with depending
of the OS version.

On Thu, Jan 5, 2017 at 4:51 AM Jeremy Grossmann <notifications@github.com>
wrote:

Well since this is a command that requires special admin rights, it is not
easy to run it from GNS3. We could eventually run it from uBridge which has
some privileges (capabilities), either programmatically or by calling
sysctl directly but I am not 100% comfortable about the idea of changing
system wide params like that.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GNS3/gns3-gui/issues/1747#issuecomment-270557765>, or mute
the thread

**Comment by grossmj** [comment]
Let's add net.unix.max_dgram_qlen=200000 in the GNS3 VM. Users should be responsible for their  systems, we should just indicate what to do in our documentation.

**Comment by sairuscz** [comment]
Thanks. In case it cannot be officially added by you, perhaps anyone interested can add the below line in gns3welcome.py right below the import statements. That is the easiest way I found to have it automatically set after the GNS3 VM boots.

/usr/local/bin/gns3welcome.py
`os.system("sudo sysctl net.unix.max_dgram_qlen=200000")`

**Comment by noplay** [comment]
I will be more to add it in the upstart and systemd script. As a comment by default but uncommented in the the version installed in the GNS3 VM.

**Comment by noplay** [comment]
It seem we can put the settings inside: /etc/sysctl.d/

**Comment by ehlers** [comment]
```
gns3@gns3vm:~$ cat /etc/sysctl.d/50-qlen_gns3.conf
# /etc/sysctl.d/50-qlen_gns3.conf - Fix for IOU AMDP2_FE-6-EXCESSCOLL
#net.unix.max_dgram_qlen=200000
net.unix.max_dgram_qlen=10000
gns3@gns3vm:~$
```
For tests I've lowered the value.

**Comment by noplay** [comment]
I will add this to the GNS3 VM script

**Comment by noplay** [comment]
Ok if you have the dev branch in GNS3 VM (1.5dev or 2.0) at next upgrade the value will be set.
