### ISSUE TITLE
Error message at initial start of wizard.

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1827]
Running GNS3 version 2.0.0dev8 on Darwin (64-bit) with Python 3.5.2 Qt 5.7.0 and PyQt 5.7.

At the initial launch (no .config/GNS3) the wizard starts (good), but shortly after an error message is shown (not that nice). After hitting the "OK" button the user can continue with the initial configuration and then the local server will successfully start. I think, that this initial error message may confuse the user.

![bildschirmfoto 2017-01-31 um 12 20 24](https://cloud.githubusercontent.com/assets/896406/22463005/0c0c0fd0-e7b0-11e6-874d-517d96821130.png)

**Comment by noplay** [comment]
You start the gui from source not from the .app? Because I don't replicate it otherwise.

If it's the case I think we should not take care of that because it will be very very complex and it will not happen to normal user because we don't ship GNS3 without the gns3server. On normal install the server start and answer even if later we will stop it to use the remote install.

The reason is the setup wizard is a child of the main window, this mean when we display the setup wizard we already load the main window and this somewhere trigger a connection to the server. This mean in all places of the main window we need to handle the case 

To be clean we should move the setup wizard before displaying anything but everything is deeply linked to the main window.

**Comment by ehlers** [comment]
Yes, I start it from the source installed in /usr/local/bin, not from the .app

If that issue not present, when starting from the .app, we can ignore it.

**Comment by noplay** [comment]
Thanks !

**Comment by ehlers** [comment]
Just removed my own GNS3 installation and installed the official v2.0b4 DMG. Same result. On my not very fast computer (it still uses hard drives) I get this error message on the initial start also when starting from the .app. I'm using an iMac (mid 2011) with OS X 10.11.6.

For me it's not a problem, but it may irritate first time users.

**Comment by noplay** [comment]
I made an improvement for not displaying error at first step of wizard
