### ISSUE TITLE
V2RC2 Edit QEMU Appliance loaded onto Remote Main Server

### ISSUE THREAD

**Issue by NealGooch** [GNS3/gns3-gui#1944]
I am running v2 RC2 with a remote main host (on an ESXi server).  I downloaded the ASAv appliance along with the asav962.qcow2 image from Cisco.

I discovered the appliance is setup to use telnet for the console but actually needs VNC.  So I went to edit the configuration of the device and ran into a couple of issues:

1) QEMU binary can't be found leading to several error messages,
2) Change the console to VNC leads to an error about VNC port numbers

As it happens I can still save the change and the appliance does actually work.

I'm guessing the gui is looking for the QEMU binary locally and not on the remote main server and I have no idea what is wrong with the VNC port number.

**Comment by noplay** [comment]
I will change the appliance to default to VNC. I have no idea why cisco stop  publishing image with serial console enabled.

Which errors messages was display about the qemu binaries and VNC console?

**Comment by noplay** [comment]
Also if you want to experiment it seem we can improve the experience:
https://gns3.com/discussions/asav-day0-iso

**Comment by vader75** [comment]
For ASAs it console is turned off due to output tty (I think GNS3 forums had this i took it from). I think VNC error is cosmetic as I can VNC (or there is some initial issue).

What I do is:


1)Work/boot via VNC

2) Device booted

#copy disk0:/coredumpinfo/coredump.cfg disk0:/use_ttyS0

3) stop device,  start again

4) change settings back to telnet/console

Then right click ASA and configure console type back to Telnet and startup output will eventually appear on putty console.

-----

Not sure if initial "console force" can be then templated to be the base image (linked image).

**Comment by grossmj** [comment]
The VIRL ASAv image works with telnet out of the box if I remember
correctly.

**Comment by noplay** [comment]
I changed the appliance file for VNC because recent Cisco images no longer have the serial and virl dropped their image :( You can no longer download it from their website
