### ISSUE TITLE
[2.0] Req/Bug? state of Vbox interface connected to shutdown device

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1945]
Hi

I connect a Linux VBox(linked clone) to IOU switch and EtherSwitch.
I start only the VBox (not the IOU switch/EtherSwitch)

In the VBox, if i do "mii-tools", the command says that the interfaces connected to the shutdown switchs are UP.
If i don't wrong, they must be DOWN.
I must have the same if i start and shutdown the IOU switch and Etherswitch

**Comment by noplay** [comment]
It's a limitation of GNS3. If we want to able to do hot link we need to have the interface ready to receive data at any time.

**Comment by Raizo62** [comment]
Idea for upgrade : when "switch" is down, you could propagate on connected Vbox to uncheck "cable connected"

**Comment by noplay** [comment]
We can't because we need to keep it running for when switch is back without
requiring to reboot vbox

**Comment by Raizo62** [comment]
I think you don't need to reboot the vbox to apply the check/uncheck to the option "cable connected" of VirtualBox. (I can do it with Graphical Interface of VirtualBox)

**Comment by noplay** [comment]
Hmm yes, after looking deeper it seem we support it for the hotlink. We already take care of modifying status of the cable.

But in this case you have a cable connected because in GNS3 the virtual cable is connected.

I see what you mean, emulate that the cable is disconnected because a side is not powered. But it's add a lot of complexity with node starting to be aware of each other internal status. I'm not sure if we can get the status of a specific interface when you run stuff like asav or iosv from the outside.

**Comment by Raizo62** [comment]
Yes, this does not work for all cases, but for some cases...

And after, I will ask for the others cases ;-)
