### ISSUE TITLE
GNS3-2.0.0: py-yarl not found

### ISSUE THREAD

**Issue by fcolista** [GNS3/gns3-gui#2015]
Hello. 
I've packaged GNS3 2.0.0 for Alpine Linux.
We ship yarl 0.10.0, but when I run gns3, i got this error:
"pkg_resources.ContextualVersionConflict: (yarl 0.10.0 (/usr/lib/python3.6/site-packages), Requirement.parse('yarl<0.10,>=0.9.8'), {'gns3-server'})"
and
"pkg_resources.DistributionNotFound: The 'yarl<0.10,>=0.9.8' distribution was not found and is required by gns3-server"

Looking at the change log, i've found in the "Version 2.0.0 rc3":
"Lock yarl version because 0.10 is not compatible with aiohttp 1.3"
I think that this is somehow related, but the aiohttp3 we ship with alpine is version 2.0.7.
Any hint? Thanks!

.: Francesco Colista
.: Alpine Linux

**Comment by noplay** [comment]
Hi,

To be honest we have lock to aiohttp 1.3 because we didn't test with the 2.0 and we where to far away in the release process to make such change. And in the past we got bad surprise when updating this.

I opened an issue in order to update aiohttp for 2.1:
https://github.com/GNS3/gns3-server/issues/1000

I think you can drop the requirements and try to use your version of yarl and aiohttp. From the changelog it seem ok.

**Comment by noplay** [comment]
Let me know if you have trouble

**Comment by antonstakhouski** [comment]
I am using archlinux and i have the same problem as fcolista. When i drop the requirments i got a
ModuleNotFoundError: No module named 'aiohttp.errors'
Seems that there is a huge API change in aiohttp since 1.3 version.

**Comment by noplay** [comment]
Thanks for the feedback. Doesn't seem a fast forward migration.
