### ISSUE TITLE
[2.1] Discussion on "available  appliances"

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2126]
Hi

I am not sure that the bar "available  appliances" is always a good idea.
- I think that is a good idea for new solo users of GNS3.  He can fastly add new devices on GNS3 if his host is correctly configured (docker,...)
- But i think also that is a bad idea in school class with students. When they are a little lost (for example, they don't see a necessary device), they click on other easy access button to try something. Then i fear that they try to install your avalaible device and be more lost.

We have already a variable "hide_new_appliance_template_button" who hide the button "new appliance template".

Can we have a variable expert_mode who hides the "new appliance template" button, and who hides also your "available  appliances" tab ? (or a new other variable for "available  appliances").
In all cases, we can access to this functionnality in "Preferences" (not implemented yet, i believe)

**Comment by noplay** [comment]
On the other hand we want the students to know that GNS3 support much more stuff. Their is still a big confusion that GNS3 is just for Cisco because they have only seen Cisco device in the interface with their teacher. One of objective to have appliance in the app is to make people curious about that. Another objective is to push people to use appliance instead of manual installation, this provide a better experience for user (every week we have support issue for ASAv because people try manual install).

Anyway I understand why you want that.

I'm  still not a big fan of the checkbox because it's create maintenance issue. It's something we will never test and that could have unwanted side effect.

I think in your case it's better to just strip the gns3a from the package. This will make an empty list. 

For school class I think at the end the correct solution will be in the web application to have something simplified easier to customize when the Qt GUI will be the expert mode.

**Comment by Raizo62** [comment]
> On the other hand we want the students to know that GNS3 support much more stuff. Their is still a big confusion that GNS3 is just for Cisco because they have only seen Cisco device in the interface with their teacher. One of objective to have appliance in the app is to make people curious about that. Another objective is to push people to use appliance instead of manual installation, this provide a better experience for user (every week we have support issue for ASAv because people try manual install).

Yes. it is a better explain of my first dot ;-) and i am agree.

> I'm still not a big fan of the checkbox because it's create maintenance issue. It's something we will never test and that could have unwanted side effect.

Don't worry, i will test for you :-)

> I think in your case it's better to just strip the gns3a from the package. This will make an empty list.

I don't understand how we do that. Which files must we to modify ?

**Comment by noplay** [comment]
When you install GNS3 you will have a directory close to the source name appliances https://github.com/GNS3/gns3-server/tree/2.1/gns3server/appliances

If you remove the content nothing will appear

**Comment by Raizo62** [comment]
( You have increase the needed version of QtPy for GNS3, then i can't test 2.1. I will beginning to work on a "stretch" debian version of LiveRaizo after summer holidays, then i will can try again.  )

> For school class I think at the end the correct solution will be in the web application to have something simplified easier to customize when the Qt GUI will be the expert mode.

Qt GUI will be the expert mode, but the "available appliances" of Qt GUI is more for beginner.

I like the customize system of GNS3 but i am not fan when a main configuration button is so easy access when i am with students.

In your choices, don't forget teachers who use GNS3 in school class ;-)

**Comment by noplay** [comment]
No no appliance are for everyone.  This is how you should add appliance to GNS3 even for expert. Really we got so much support trouble because people don't use appliances. Community put huge effort to make proper template with proper settings and we still have user using the wrong settings. 

If you don't want to see them you can just select Installed appliance we will remember the settings between sessions, but appliance will be available when you will need them. 

It's one of our biggest complaint. People telling us GNS3 is hard to configure. Especially with students that previously used a preconfigured version at school thinking GNS3 is broken because no appliance is available.

The correct answer is too have multiple interface depending of the use case.

**Comment by noplay** [comment]
Note: we will probably not have an interface perfect for your use case because you don't want all the feature but you use advanced stuff like Vbox linked clone. 

You will probably have an interface with no settings at all for employee and students that don't need to configure GNS3.

**Comment by noplay** [comment]
I think we will see the feedback of the alpha. 

 Perhaps we will need to improve the wizard to make it clear what's happen when you try to use the appliance. Because if it's not clear for your students it's not clear for everyone.

**Comment by Raizo62** [comment]
> I think we will see the feedback of the alpha.

Ok :-) but think to distinguish the feedback of beginner and teachers of class rooms.

> Because if it's not clear for your students it's not clear for everyone.

Just to be clear : now, i use with my students GNS3 2.0. They are surprised that default install of GNS3 is empty while with my LiveRaizo, GNS3 is ready to use.
With 2.1, i am agree that the configuration will be more fast and easy.

> Perhaps we will need to improve the wizard to make it clear what's happen when you try to use the appliance. 

Don't forget that (my) students hate reading ;-) (It is a big problem :-( )

I insist : I ask to move the "add appliance" into preference menu. I don't ask to remove it (beginner or expert mode)

**Comment by noplay** [comment]
Yes I understand but you don't imagine how much people start by asking on
the forum before going to the preference menu :(

A lot of user hate reading :( We tried to improve documentation but still
have this issues .....
