### ISSUE TITLE
Question : rename project with cloned virtualbox

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2168]
Hi

I believe that we can't rename ("save as") project with clone virtualbox because VirtualBox keeps a bad file name. (sorry, i don't found the old closed issue where we talk of this functionnality).

In changelog of the new release of VirtualBox 5.1.24, i have see this message : 
> API: use the correct file name of the VM machine state if the VM settings directory is renamed, for example during grouping / ungrouping a VM (bugs #16075 and #16745)

Perhaps that the bug of virtualbox necessary to rename project is resolved.

**Comment by noplay** [comment]
Hi,

We can't save as a project with virtualbox because  we can't just import / export project (save as use that under the hood). 

We use the import / export code for multiple reason, but the main reason is it's more simple and reliable. We snapshot everything at file system level and restore it in a new location. This mean the same code work for moving a project to the same computer and to another computer.

**Comment by Raizo62** [comment]
But, we can import/export VM with VirtualBox (import/export Appliances) , can't we ?

**Comment by noplay** [comment]
You can't export from GNS3, for the same reason everything is not accessible from the file system. This require specific code to support it and we prefer to invest time in better support of Qemu.

**Comment by Raizo62** [comment]
Don't lost cloned virtualbox (while we cannot share variable/directory without network in QEmu). I need it ;-)

**Comment by LinuxOnTheDesktop** [comment]
I think I have the same problem. To reproduce:
1) clone a VM, within the virtual box app;
2) delete the VM from which the clone was made;
3) try to rename the clone to the name of the old VM.

These steps are intuitive and people will do them in order to achieve an understandable goal. At present, that goal will not be attained. I myself am stuck with a VM called 'Win 10 home clone'.
