### ISSUE TITLE
[2.0.3] Progress window for image upload is not accurate

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#2188]
In GNS3 2.0.3 on Mac or Windows when you upload a new file, the progress window goes to 95-98% very fast, even though only a couple of MB of an image was really uploaded.
Reproducible 100%, during an image upload I logged into the server and checked .tmp file size in **/opt/gns3/images**

**Comment by noplay** [comment]
We are aware of that. But because the client is not doing the uploading we can't make it accurate without heavy work. This require extensive use of websocket for getting the progress instead of being able to use Qt informations.

**Comment by dmfigol** [comment]
@noplay Would it be possible to get some estimate? For example, get current upload speed every X seconds and based on that, evaluate the speed of filling progress bar?
Currently it is way off base.

**Comment by noplay** [comment]
Same issue. We can't without heavy work.

What happen is the client make an HTTP call to the server. The server will upload the image to the other server. But the original HTTP call is very light and block until the progress is done.

To do a progress we need to transmit the info and update the progress dialog.  It's not simple. I keep the issue open, but not for current release because the progress dialog is already complex and a source of application crash.

**Comment by grossmj** [comment]
Fixed in version 3.0 (to be released).
