### ISSUE TITLE
Cannot export a portable project with GNS3 VM

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2271]
https://gns3.com/qa/cannot-export-a-portable-project

**Comment by ziajka** [comment]
I think I'm able to reproduce the issue.

**Comment by ziajka** [comment]
I confirm that both cases exist:
1. Export project cannot be exported when it's connected to GNS3VM with images.
2. Export project cannot be exported when it's connected to GNS3VM with no images.

With images moved to the Windows host it's possible to do export, however even with option 2. files are being downloaded and included into file.

**Comment by ziajka** [comment]
If anybody has experienced  this issue here is the guide how to transfer files:

![transfer-images-from-gns3vm-to-host](https://user-images.githubusercontent.com/29223277/31216302-6e273134-a9b3-11e7-82cf-e51761ac0915.gif)

Credentials to GNS3 VM are:
- login: gns3
- password: gns3

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/pull/1227

**Comment by Karlheinzniebuhr** [comment]
Having the same issue on Win10 with GNS3 2.1.8

**Comment by qcdebug** [comment]
I think I'm having a similar issue when running a bare metal remote server.   The export eventually fails with cannot access file (that it was currently writing) file in use by another process.   I'm waiting for it to fail again so I can copy it verbatim.    Could this have to do with the 1200 second timeout that is present when issuing VM commands?

**Comment by qcdebug** [comment]
Cannot export project: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Miranda\\AppData\\Local\\Temp\\tmpwik_jfxx\\tmp72j5wvd5'

At the time of the error, the file size is 22,861,928,986 bytes. It also appears to fail about the same byte range every time though I did see one fail at about 19GB as well in the times I've been checking the failure sizes.
