### ISSUE TITLE
Project cannot be duplicated

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2306]
Investigate this issue: https://gns3.com/discussions/warning-projects-don-t-duplicate

**Comment by ziajka** [comment]
I'm not able to reproduce the issue on version 2.0.3 and 2.1.0rc3 - case when project is duplicated but no files created.

However I think issue is because when you try to duplicate running project you get just information "Error while duplicate project: Running topology could not be exported" in Console, which may be closed so you cannot see it. In the end project is not duplicated. In 2.1.0 we display errors in more user friendly way.
