### ISSUE TITLE
Any project created when gns3 service is disabled cannot be accessed when gns3 service is enabled.

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#2421]
Ubuntu 17.10
gui & server 2.x

If I create a project with gns3 GUI when gns3 is stopped with ```systemctl stop gns3```, exit the GUI, start gns3 service with ```systemctl start gns3``` and reload the GUI, the original project cannot be loaded anymore and I get: 
```CRITICAL __init__.py:222 Error transferring http://<user's uuid>@127.0.0.1:9000/v2/projects/load - server replied: Forbidden```. 
The user's UUID is defined in ~\.config/GNS3//root/.config/GNS3/gns3_server.conf as ```user = <user's uuid>```.

That's annoying because I have to stop & disable gns3 service each time I install a new version of GNS3 server.
Is there a way to allow all projects to be loaded with or without gns3 service running on the local host?

**Comment by ziajka** [comment]
Hi @jean-christophe-manciot,
How do you open the project? (I know this question may look as not connected to the subject but probably it is)
Thanks,
Dominik

**Comment by grossmj** [comment]
@jean-christophe-manciot ping? ;)

**Comment by jean-christophe-manciot** [comment]
@grossmj @ziajka 
I open the project through the GUI.

**Comment by cioby23** [comment]
I have experienced this bug also. (Environment; GNS3 server (v. 2.1.10dev2): Linux (Archlinux) Python 3.7 and GNS3 GUI (v. 2.1.10dev2) local Archlinux and remote Windows 7)
I am using my home PC as GNS3 server and I'm accessing it locally using GNS3 GUI (Linux) and sometimes remotely using GNS3 GUI (Windows)
Steps to reproduce:
1. Open GNS3 GUI locally with gns3server systemd service stopped and open an existing project. (loads fine)
2. Open GNS3 GUI locally with gns3server systemd service enabled and running. The GUI tries to open its own local instance of gns3server besides the one which runs on systemd.
![gns3-server](https://user-images.githubusercontent.com/7124193/44925193-5fbfd400-ad56-11e8-9e7d-3742fec9ce38.png)
3. Try to create a new project or open an existing one. The GUI returns the following error.
![image](https://user-images.githubusercontent.com/7124193/44925221-7c5c0c00-ad56-11e8-82e4-d6ae03e489a9.png)
4. If running GUI on remote machine the gns3server service needs to be running otherwise it cannot connect.

I suggest that the GNS3 GUI on local machine should to try to detect existing gns3server running as a service and connect to it instead of spawning a new local instance which requires to shutdown the service in order to connect locally.

**Comment by cioby23** [comment]
As a workaround I have edited the systemd service for gns3server and besides the --host and --port options I have added --local flag and now both local and remote GUI connect to the same instance of gns3server service.
**cat /lib/systemd/system/gns3-server.service 
[Unit]
Description=GNS3 server for %i

[Service]
Type=simple
User=<username>
ExecStart=/usr/bin/gns3server --local --host 192.168.1.3 --port 8080 --log /home/cioby/.config/GNS3/gns3_server.log
Restart=on-failure**
