### ISSUE TITLE
Invalid answer from the PyPi server

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#2473]
2.1.4 with remote server.

Received the following console message this morning when loading a project:

=> Invalid answer from the PyPi server

=== GNS3 2.1.4 traceback on 17 Apr 2018 10:10:21 ===
Traceback (most recent call last):
  File "./gns3-gui/gns3/update_manager.py", line 135, in _pypiReplySlot
  File "./gns3-gui/gns3/update_manager.py", line 158, in _getLastMinorVersionFromPyPiReply
TypeError: string indices must be integers

The error can be seen again when asking to check for update.  Obviously there is no update available now, but I just wanted to report a potential problem :)

**Comment by grossmj** [comment]
Apparently you discovered this issue because you have enabled "experimental features" in the preferences. Just to be sure, what OS do you run GNS3 on?

![experimental_feature](https://user-images.githubusercontent.com/4752614/38915388-0a228e5c-4316-11e8-9777-4762b88396bc.png)

I will fix this problem. Thanks for catching that.

**Comment by grossmj** [comment]
The error is because PyPi changed their URL from `https://pypi.python.org/pypi/gns3-gui/json` to `https://pypi.org/pypi/gns3-gui/json`.

Their is a 301 permanent redirect for the old URL but our code didn't support redirections. Now this is supported if you have Qt version >= 5.6.0.

Also catching invalid replies (not JSON) now.
