### ISSUE TITLE
The virtual machine appears as 2.1.9 after the update.

### ISSUE THREAD

**Issue by JBSecvrity** [GNS3/gns3-gui#2591]
"
![inkedcaptura_li](https://user-images.githubusercontent.com/42786604/45595917-e6f68400-b9b3-11e8-9727-1d2696b381b7.jpg)
GNS3 controller version 2.1.10 is not the same as compute server GNS3 VM (GNS3 VM) version 2.1.9"

**Comment by ehlers** [comment]
Yeah, the upgrade procedure of the GNS3 VM is quite flaky. Here my experiences with upgrading a pristine v2.1.9 GNS3 VM.

1. Issue: open-vm-package is not updated correctly
  After the first upgrade the open-vm-tools package is not installed correctly, no matter if you answer Y(es) or N(o) to the question about using the updated tools.conf. Re-doing the upgrade solves this issue.
  ![gns3-vm_update](https://user-images.githubusercontent.com/896406/45597968-79a71b00-b9d4-11e8-8b52-4dadeb3d92da.png)

2. GNS3 version stays at v2.1.9
  The reason is, that the upgrade procedure uses the last line of `git tag -l 'v2.1*'` to get the latest version. But `git tag` sorts alphabetically, so the last line is v2.1.9. The output of `git tag`should be sorted by `sort -V`, then v2.1.10 will be on the last line.

```
gns3@gns3vm:~/gns3-server$ git tag -l 'v2.1*' | grep -v '[abr]' | tail -n 1
v2.1.9
gns3@gns3vm:~/gns3-server$ git tag -l 'v2.1*' | grep -v '[abr]'
v2.1.0
v2.1.1
v2.1.10
v2.1.2
v2.1.3
v2.1.4
v2.1.5
v2.1.6
v2.1.7
v2.1.8
v2.1.9
gns3@gns3vm:~/gns3-server$ git tag -l 'v2.1*' | grep -v '[abr]' | sort -V | tail -n 1
v2.1.10
```

Workaround until this gets fixed: update the gns3server manually

Start a shell and enter the following commands:

```
cd ~/gns3-server/
git checkout v2.1.10
sudo pip3 install -U -r requirements.txt
sudo python3 setup.py install
sudo reboot
```

**Comment by grossmj** [comment]
I just fixed with a more complicated command line ;) Please try again.

**Comment by JBSecvrity** [comment]
Solved and working properly, thanks to the instructions provided by ehlers (https://github.com/ehlers).
 Thank you very much for responding and also make it so fast.

**Comment by grossmj** [comment]
@ehlers I am going to check how I can fix the open-vm-tools issues and investigate why the old procedure is used on second update.

**Comment by grossmj** [comment]
I've fixed all the upgrade issues. Everything should work on first upgrade. That being said there are still some inconsistencies that we should aim to fix when we migrate the GNS3 VM to the latest Ubuntu LTS.
