### ISSUE TITLE
Review how certain things are named

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2635]
Currently we have the following glossary: http://api.gns3.net/en/2.2/glossary.html

I am wondering if we should make the following changes:

- A topology can also be called a project.

- Appliance should be renamed to "Node template". For me appliance may not be accurate enough and could be confusing. I prefer node template because this is literally what we it is, node template settings are used to create a new node.

- Appliance template could be just be renamed "appliance". An appliance is used to create a new node template.

- Compute should be referred as "Compute server".

I am especially undecided about appliances and appliance templates. Edit: I was already thinking about it some time ago: https://github.com/GNS3/gns3-gui/issues/2490#issuecomment-414291707. 

What do you think? Are the current names good enough? Is there anything else that should be named differently?

**Comment by grossmj** [comment]
@ehlers I would love to see you comments on this. Thanks :)

**Comment by adosztal** [comment]
I agree with the topology = project.

Compute is an interesting one because in the cloud era people often refer to servers as compute. In their view it would be "server server". :)
Is there going to be another server than compute? If yes, "compute" will distinguisher; if not, "server" is just additional characters in a string.

For the appliance, the problem is that people on the forum use these terms quite loosely. E.g.
- "I imported this appliance."
- "I pulled the appliance to the topology; then started it but it doesn't boot."
- "I pulled the node to the topology; then started it but it doesn't boot."

So maybe we should refer to the objects in the topology as "nodes", use the "appliances" for the files used to import stuff, and use simply "templates" for the things in the left panel - but make a note at the bottom of the page that people often use these terms interchangeably.

**Comment by grossmj** [comment]
Thanks for your comments. I will make sure we are consistent on the naming.

- "Compute" will remain compute. I will check if we named anything "Compute server" and change this to simply use "compute".

- "Node" will remain node too. We already pretty consistent for this.

- "Project" is already almost used everywhere in GNS3 gui/server, I will make sure this is the case. I think the "topology" term is used a lot more in the documentation. I will see if we need to update this.

- There are a few places where we use "Appliance template" to refer to appliances (the files that you can download from gns3.com). I will make sure we just use "appliance".

- We will use "templates" to for the things that are used to create new nodes, in the GUI they are in the left panel and preferences. The new appliance management API endpoints (in 2.2) will be changed to reflect this.

**Comment by grossmj** [comment]
Done.
