### ISSUE TITLE
Please support others languages like Chinese

### ISSUE THREAD

**Issue by ykla** [GNS3/gns3-gui#2731]
**Is your feature request related to a problem? Please describe.**
longer supports switch others languages after version 0.8. GNS3 only supports English now.

**Describe the solution you'd like**
Just support it.

**Describe alternatives you've considered**
Why not give language packs choice.

**Additional context**
I don't  know why you not supports others languages, Do we around the world must be good  at English then they could use GNS3?

**Comment by grossmj** [comment]
We have some reasons why we don't support other languages, this is mostly about consistency and administrative reasons:

- Most appliances only support English, for instance running a Cisco IOS will show a CLI in English. This does not present a consistent environment.

- Most of our software dependencies will show info and error/warning messages in English only. This is not consistent too.

- It creates delays and other issues since we would have to depend on translators, for instance changing one sentence in GNS3 would require us to contact all the translators to update their translation. This could be done on a major release basis but this is still an administrative burden. Also, it is hard to check the quality of the translation.

- More generally, it is expected that I.T. professionals can understand a minimum of English to perform their job. I agree this is very debatable (my first language is not English).

- We haven't had many requests to support other languages. We think most of our users are fine with English only.

So after weighing the pros and the cons, we decided it was not worth it to support other languages.

**Comment by ykla** [comment]
I think you should give some  writable configuration files for languages so that others can translate them by themselves and not just unsupported other languages.
