### ISSUE TITLE
Opening previously saved 2.1 project grid overlapping

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-gui#2734]
**Describe the bug**
Grid of old saved 2.1 projects overlaps with grid from 2.2 gns3-gui

**GNS3 version and operating system (please complete the following information):**
 - OS: Linux
 - GNS3 version [2.2.0 dev 6]
 - Local server

**To Reproduce**
1. Open an existing 2.1 project.
2. Click on View --> 'Show the grid' option
3. Displayed grid is overlapping (check below screenshot)
4. Issue appears when using non-default value for node grid size (e.g. 55)

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/7124193/54234411-bbde8e80-4517-11e9-985f-b52bbf4133b0.png)

**Additional context**
When creating a new project in version 2.2 or importing a 2.1 project using default node grid size of 75 it looks fine.

**Comment by grossmj** [comment]
This is because we introduced a new grid for drawings in 2.2 with a default size of 25, so importing a 2.1 project that uses a non-default value for node grid size shows something that look like overlapping grids.

![edit_project](https://user-images.githubusercontent.com/4752614/55287570-e3b56980-53d4-11e9-8422-4ac4c38841be.png)

I have added some conversion code so any 2.1 project (< revision 9 in the .gns3 file) that does not contain a drawing grid size will get one of the same size of the grid size value.

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/commit/21bed54768f51c818f3aa6550dddc37b5c9f232a
