### ISSUE TITLE
What is branch master good for?

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2830]
When you compare the latest 2.2.0b4 release with master, you see some commits, that never made it into any release.

https://github.com/GNS3/gns3-server/compare/v2.2.0b4...master
https://github.com/GNS3/gns3-gui/compare/v2.2.0b4...master

Some are appliance updates, that should have been added to gns3-registry. But there are other goodies, like the web-ui v2019.2.0-alpha.5.

Those commits will never be used, the master branch seem to be totally superfluous. For me the master branch is like an black hole. Or have I overlooked something.

**Comment by grossmj** [comment]
We have identified this problem few months ago and we plan to use the master branch as our main development branch once we release the final version of 2.2, we don't really want to do it now because we are worried to break our build tools/process.

Things look okay on gns3-gui since most of these changes are just to display information on GitHub. However we missed a few things on server repository. I merged a few PRs that I thought were for the gns3-registry repository, I will fix this soon.

Also, the web-ui v2019.2.0-alpha.5. made it to 2.2 beta 4 but I cannot see any commit regarding this on our 2.2 branch, I guess this may be because of the way we package the webui when we released. @ziajka do you have any explanation?

**Comment by ziajka** [comment]
Hey @grossmj All the commits should be on master. Temporary we should merge master into 2.2 before releasing, this would keep our existing build process untouched.

**Comment by grossmj** [comment]
Ok, let's do this from now on then.
