### ISSUE TITLE
Improve Release Process

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2851]
Quality of the 2.2.0rc releases:

| Version | Status |
| --- | --- |
| 2.2.0rc1 | Packages don't build, invalid jsonschema version 3.2.0 |
| 2.2.0rc2 | Windows GUI doesn't run, cx_Freeze seems incompatible with jsonschema 3.0.2 |
| 2.2.0rc3 | OK |
| 2.2.0rc4 | GNS3VM  doesn't show menu, dialog package missing |

During software development errors are normal, so nobody is to blame. But releases should at least start and the basics should work. In 3 of 4 releases that's not the case. It seems, that GNS3 is totally untested before releasing.

I have no insight of the release process, but I think there's room for improvement.

**Comment by grossmj** [comment]
I agree, the release process should be improved.

What happens is everything is built using Appveyor, CircleCI and on-demand servers and then the installers/VMs are published on GitHub/Sourceforge.  GNS3 is tested before releasing excepting the actual builds themselves which can be broken by external dependencies like cx_freeze and jsonschema. Also, the 2.2.0rc4 VM is broken due to changing the Ubuntu version from 18.4.2 LTS to 18.4.3 LTS, still need to investigate the exact reason. It is usually too late and there is no chance to go back once we start a new release.

Another issue is the VMs require the GNS3 Debian packages to be built but those packages cannot be re-published with the same version number if something is wrong with them, we must release a new version.

Here are some ideas to improve the release process:

* Test the latest nightly builds on Windows/macOS and do not make any changes before releasing a new version.
* For the VMs, we should build a pre-release version and test that everything works before the actual release. I don't know how yet.

Any other ideas is welcome.

**Comment by jtorri** [comment]
Just a thought or two.  Perhaps we are forgetting GNS3 is a remarkably useful piece of software that required years of development and testing to which we have full access for free.  The primary question, IMHO, seems to be how to provide fairly thorough, useful and controlled testing prior to release (as well as after) for free. As if evident in the latest release, 2.2.0rc5, after a few struggles it is possible to build and learn from a fairly complex network (routers, switches, firewalls, windows and linux servers and clients. etc,) for the cost of a VIRL subscription. Not bad.
