### ISSUE TITLE
Missing Ubuntu packages for 2.2.2

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2891]
**Describe the bug**

For Ubuntu 19.04 (Disco) the version 2.2.2 failed to build and is therefore missing, see
https://launchpad.net/~gns3/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=disco

For Ubuntu 19.10 (Eoan) the latest version is 2.2.0, v2.2.2 (and v2.2.1) is missing, see
https://launchpad.net/~gns3/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=eoan

**GNS3 version and operating system (please complete the following information):**
 - OS: Ubuntu Linux 19.04 and 19.10
 - GNS3 version 2.2.2

**Comment by grossmj** [comment]
Correct, I was having issue releasing for Disco. Thanks for reminding me about Eoan though.

Looks like the build problem is due to the latest psutil version https://pypi.org/project/psutil/#history somehow it has broken our builds :/ I forced the use of the previous version and everything has been successfully built.
