### ISSUE TITLE
Node grid overlaps with drawing grid, after changing the values from preferences.

### ISSUE THREAD

**Issue by n3oxmind** [GNS3/gns3-gui#2908]
GNS3 v2.2.3

I usually change the grid size to make a good use of the snap to grid function. But with the new gns3-gui version (2.2.3) the node grid has been introduced and it messing up the workspace with overlapped lines.

how to replicate:
form preferences change the value of node grid and open new project to see changes.

screenshot
![image](https://user-images.githubusercontent.com/10103340/69910128-04e2b580-13bb-11ea-856d-a31dbf5ba79d.png)

I advice to correlate the two grids values into one value. The node grid size should be changed based on the drawing grid size.

my current resolution is just removing the node grid completely from `graphics_view.py` until it get fixed:
original version
```
grids=[(self.drawingGridSize(),QtGui.QColor(208,208,208)),                                                                                             
       (self.nodeGridSize(), QtGui.QColor(190, 190, 190))]
```
modified version
```
grids=[(self.drawingGridSize(),QtGui.QColor(208,208,208))]                                                                                            
```

Thanks,

**Comment by cioby23** [comment]
I had this issue a while ago. This happens when you use values for the node grid and drawing grid which when divided results in floating numbers instead of integers.
For example if I set the node grid size to 60 then for the drawing grid I need to use values which directly divided with the value of the node grid size like (e.g. 60,30,20,15,10,5)
If you set for example 50 for the node grid size and 20 for the drawing grid size you'll experience the overlapping lines issue since 50/20 is 2.5 which is not an integer value.

**Comment by grossmj** [comment]
@cioby23 do you think we should prevent users from configuring node grid sizes resulting in a floating number?

**Comment by cioby23** [comment]
@grossmj we can try and force only predefined values for the node grid by checking the modulus of the division between drawing grid size and node grid size and if the remainder is different than zero then do not allow that value to be used. (e.g. 50%20 = 2 remainder value 10 - do not allow)
Also a message might be added specifying that only direct proportional numbers between drawing/node grid size must be used

The other way as @n3oxmind mentioned might be to unify both grids values into a single one.

**Comment by grossmj** [comment]
Fixed.
