### ISSUE TITLE
Is there a hook or placeholder where a progammer could insert his code to be executed from t he GUI?

### ISSUE THREAD

**Issue by 1001QAdotNET** [GNS3/gns3-gui#2946]
I am working on a couple of scripts that work via REST API and I would like to be able to execute them from a menu either from the GUI of from the WebUI
Where could one less experienced programmer insert this type of code?
Ideally it would be nice if you can select certain devices and they run the code on those devices. I guess what I am asking is how do I access the list of selected nodes or edges programmatically

**Comment by b-ehlers** [comment]
See issue [A plugin system #708 (comment)](https://github.com/GNS3/gns3-gui/issues/708#issuecomment-529929063)

I wrote a blog post about that: https://www.bernhard-ehlers.de/blog/2018/01/12/gns3-integrate-programs.html

I'm using it since the early days of 2.1. But adding this or something similar into the official GNS3 GUI seems to have low priority, the milestone gets shifted further and further away. So you shouldn't expect it in the next few years. You can use my patches, but then you have to build your own GNS3 GUI.

**Comment by b-ehlers** [comment]
There are already two similar issues for that: https://github.com/GNS3/gns3-gui/issues/1087 (from you) and https://github.com/GNS3/gns3-gui/issues/708

**Comment by grossmj** [comment]
> I am working on a couple of scripts that work via REST API and I would like to be able to execute them from a menu either from the GUI of from the WebUI

Yes, this is on the roadmap already.

> Ideally it would be nice if you can select certain devices and they run the code on those devices. I guess what I am asking is how do I access the list of selected nodes or edges programmatically

This one could be really problematic to implement. Unfortunately, not a priority for now

**Comment by b-ehlers** [comment]
> > Ideally it would be nice if you can select certain devices and they run the code on those devices. I guess what I am asking is how do I access the list of selected nodes or edges programmatically
> 
> This one could be really problematic to implement. Unfortunately, not a priority for now

That's already implemented in my plugin system https://github.com/GNS3/gns3-gui/issues/708#issuecomment-529929063

**Comment by b-ehlers** [comment]
@1001QAdotNET: A poor man's solution is to use custom console applications, see first part of https://www.bernhard-ehlers.de/blog/posts/2018-01-12-gns3-integrate-programs/
