### ISSUE TITLE
Firefox on gns3 error

### ISSUE THREAD

**Issue by silvereyez1** [GNS3/gns3-gui#2950]
Hello Folks,
I installed a firefox appliance which i would like to connect to NAT node in GNS3.
I get the following error when i turn on the device.

Error while sending command 'bridge add_nio_ethernet b01783f8-e3cf-42a4-99ff-1e705d06dc30-0 "\Device\NPF_{E6C7FA25-FC09-44B1-B22C-70E10E5488F1}"': unable to create NIO Ethernet for bridge 'b01783f8-e3cf-42a4-99ff-1e705d06dc30-0': uBridge version 0.9.16 running with WinPcap version 4.1.3 (packet.dll version 10, 2, 0, 5002), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
Hypervisor TCP control server started (IP localhost port 52264).
UDP tunnel connecting from local port 10000 to IPv4 addresss 192.168.137.128 on port 20000
nio_ethernet_open: unable to open device '\Device\NPF_{E6C7FA25-FC09-44B1-B22C-70E10E5488F1}': Error opening adapter: The operation completed successfully. (0)

Any advice on this will be appreciated.

**Comment by grossmj** [comment]
Not sure what is going on with this error but you can try to execute this command with cmd.exe as an Administrator: `netsh winsock reset`

**Comment by silvereyez1** [comment]
Hi ,
I actually tried this before but didnt work...its quite frustrating i had to unwillingly uninstall gns3 ..still didnt work.
any other way out you could suggest ?

**Comment by grossmj** [comment]
I would recommend to use the NAT device from inside the GNS3 VM.

**Comment by silvereyez1** [comment]
hello,

Thank you for recommendation. I tried this and it did work when i used inside GNS3 VM on firefox appliance.

But same error is now showing up when i connect a fortigate device to cloud...for example i used the vmnet1 on cloud to connect to fortigate . As soon as i turn the device device on i get this error.

**Comment by cioby23** [comment]
@silvereyez1 the screenshots above are not from the NAT node but cloud node instead. You mentioned in the first post that you would like to connect to NAT node.
The NAT node does not have a configuration dialog as the cloud node but is uses the same symbol as the cloud node. 
Maybe it's better to change the symbol so that no confusion would be made between NAT and cloud nodes
Here is a picture of the NAT node in the Devices list
![nat](https://user-images.githubusercontent.com/7124193/77054149-0f5fa400-69d8-11ea-9652-7cc232add5f8.png)
Also if you're not using GNS3 VM make sure the libvirtd service is running.

**Comment by silvereyez1** [comment]
Hello folks,
Issue was resolved. 
Thanks for all advice.
