### ISSUE TITLE
Cant skip slots

### ISSUE THREAD

**Issue by yoctox** [GNS3/gns3-gui#3000]
**Describe the bug**
Can't populate slots 4,5,6 with slots 1,2,3 unpopulated on 7200 router. Can't leave slot 0 unpopulated which was possible in earlier releases.

**GNS3 version and operating system (please complete the following information):**
 - OS: macOS 10.1.5.5
 - GNS3 version 2.2.8
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.) Local server

**To Reproduce**
1. Slot 0 cannot be left unpopulated
2. If slots 123 are left unpopulated, with 4,5,6 populated with say GE connector, the GUI shows incorrect network connections.

Behaviour was different in versions of GNS before 2.0

**Comment by yoctox** [comment]
Thanks for responding grossmj. I've not reported a bug on github before.

**Comment by grossmj** [comment]
No worries, I am going to investigate.

**Comment by yoctox** [comment]
Thanks Jeremy. Ideally what I'd like to be able to setup is a 7200 router template with all the slots empty. Currently GNS3 adds a C7200-IO-FE adapter to slot 0 be default. I'd also like the option to add a PA-GE adapter to individual slots in specific 7200 router nodes on the workspace. The interface labels should then show the correct interface ie g1/0, g2/0 etc. The pre-2.0 version of GNS3 allowed one to do this.

**Comment by grossmj** [comment]
> Slot 0 cannot be left unpopulated

An adapter in slot 0 is mandatory with c7200. This is a special adapter (I/O controller). In previous version this could be left empty but a `C7200-IO-FE` adapter was silently added by Dynamips.

I wouldn't recommend other adapters for slot 0 because I remember I had issues with `C7200-IO-GE-E` for instance. Also, when launching dynamips,  `C7200-IO-2FE` and `C7200-IO-GE-E` are marked as NOT WORKING. So just to be safe I would stick with `C7200-IO-FE`

```
$ dynamips 
Cisco Router Simulation Platform (version 0.2.21-amd64/Linux stable)
Copyright (c) 2005-2011 Christophe Fillot.
Build date: May 19 2020 11:38:40

...
Available C7200 Port Adapter (PA) drivers:
  * NPE-G2 
  * C7200-IO-FE 
  * C7200-IO-2FE (NOT WORKING)
  * C7200-IO-GE-E (NOT WORKING)
```

> If slots 123 are left unpopulated, with 4,5,6 populated with say GE connector, the GUI shows incorrect network connections.

![Screenshot from 2020-06-26 21-57-56](https://user-images.githubusercontent.com/4752614/85856992-27756980-b7f8-11ea-94e7-cf86c6a0f8a2.png)

Correct, there is a problem with the network connection labels.

![Interfaces](https://user-images.githubusercontent.com/4752614/85857198-89ce6a00-b7f8-11ea-81d0-b941a9da8463.png)

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/ea17cc2565147a0b759480e22c49225c045ccd84
