### ISSUE TITLE
macOS Big Sur - fails to launch

### ISSUE THREAD

**Issue by i0nicsBik** [GNS3/gns3-gui#3037]
**Describe the bug**
Fails to launch in macOS big sur

**GNS3 version and operating system (please complete the following information):**
 - OS: macOS
 - GNS3 version 2.2.7

**To Reproduce**
1. Download and Open

**Comment by i0nicsBik** [comment]
Any workaround or fixes?

**Comment by grossmj** [comment]
> Any workaround or fixes?

Yes, that would be to manually install GNS3 using Python pip etc.

**Comment by i0nicsBik** [comment]
Can you please explain or provide a link on how to do that? @grossmj

**Comment by grossmj** [comment]
I understand that macOS Big Sur will be released later in 2020. We will wait for the final release.

**Comment by i0nicsBik** [comment]
It will be released tomorrow. Please try to fix whatever the issue is. Thanks!

**Comment by grossmj** [comment]
We will try to work on it for the next release.

**Comment by grossmj** [comment]
Still waiting for the final release.

**Comment by Vardiak** [comment]
macOS Big Sur is expected to launch tomorrow, this should be prioritized...

**Comment by tthoma24** [comment]
> Still waiting for the final release.

Access to the beta has been and still is available. Has work started on this, and if not, how can I help?

**Comment by grossmj** [comment]
> Access to the beta has been and still is available. Has work started on this, and if not, how can I help?

We don't have a Mac to do tests, we use VMs instead. We will test very soon. Please can you try to launch the latest version of GNS3 and let us know if you see any error message or any logs? Thanks :+1:

**Comment by tao-lian** [comment]
MacBook Pro with Big Sur RC (20B5022a)
GNS 3 2.2.16

Launch just hang, no error message. crash report

Date/Time:        2020-11-10 10:44:26.096 +0000
End time:         2020-11-10 10:44:49.154 +0000
OS Version:       macOS 11.0.1 (Build 20B5022a)
Architecture:     x86_64h
Report Version:   32

Data Source:      Stackshots
Shared Cache:     A9737087-3974-36EB-9847-CD5DDC366BFB slid base address 0x7fff20036000, slide 0x36000

Command:          gns3
Path:             /Applications/GNS3.app/Contents/MacOS/gns3
Identifier:       net.gns3
Version:          2.2.15 (GNS3 v2.2.15)
Parent:           launchd [1]
PID:              34577
Time Since Fork:  32s

Event:            hang
Duration:         23.06s
Duration Sampled: 5.20s (process was unresponsive for 18 seconds before sampling)
Steps:            52 (100ms sampling interval)
Report threshold: 2.5s

Hardware model:   MacBookPro16,1
Active cpus:      16
Boot args:        chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 96450s
Time Since Wake:  88679s

Fan speed:        2730 rpm -> 3039 (+309)

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------


Heaviest stack for the main thread of the target process:
  52  start + 1 (libdyld.dylib + 87601) [0x7fff2035e631]
  52  main + 661 (gns3 + 6293) [0x10311d895]
  52  _PyObject_FastCallDict + 196 (Python + 42760) [0x103134708]
  52  _PyFunction_FastCall + 121 (Python + 696809) [0x1031d41e9]
  52  _PyEval_EvalFrameDefault + 1659 (Python + 661025) [0x1031cb621]
  52  call_function + 450 (Python + 692413) [0x1031d30bd]
  52  _PyFunction_FastCall + 121 (Python + 696809) [0x1031d41e9]
  52  _PyEval_EvalFrameDefault + 1659 (Python + 661025) [0x1031cb621]
  52  call_function + 491 (Python + 692454) [0x1031d30e6]
  52  _PyCFunction_FastCallDict + 166 (Python + 274437) [0x10316d005]
  52  builtin_exec + 547 (Python + 649846) [0x1031c8a76]
  52  PyEval_EvalCode + 42 (Python + 659244) [0x1031caf2c]
  52  _PyEval_EvalCodeWithName + 1747 (Python + 694374) [0x1031d3866]
  52  _PyEval_EvalFrameDefault + 1659 (Python + 661025) [0x1031cb621]
  52  call_function + 450 (Python + 692413) [0x1031d30bd]
  52  fast_function + 218 (Python + 696137) [0x1031d3f49]
  52  _PyEval_EvalCodeWithName + 1747 (Python + 694374) [0x1031d3866]
  52  _PyEval_EvalFrameDefault + 1659 (Python + 661025) [0x1031cb621]
  52  call_function + 491 (Python + 692454) [0x1031d30e6]
  52  _PyCFunction_FastCallDict + 166 (Python + 274437) [0x10316d005]
  52  meth_QApplication_exec_(_object*, _object*) + 80 (QtWidgets.so + 161504) [0x106c476e0]
  52  QCoreApplication::exec() + 130 (QtCore + 2067970) [0x103ee7e02]
  52  QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431 (QtCore + 2050191) [0x103ee388f]
  52  ??? (libqcocoa.dylib + 235103) [0x10862965f]
  52  -[NSApplication run] + 586 (AppKit + 195546) [0x7fff22c3dbda]
  52  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366 (AppKit + 251723) [0x7fff22c4b74b]
  52  _DPSNextEvent + 883 (AppKit + 257925) [0x7fff22c4cf85]
  52  _BlockUntilNextEventMatchingListInModeWithFilter + 64 (HIToolbox + 199407) [0x7fff2869daef]
  52  ReceiveNextEventCommon + 283 (HIToolbox + 199714) [0x7fff2869dc22]
  52  RunCurrentEventLoopInMode + 292 (HIToolbox + 200656) [0x7fff2869dfd0]
  52  CFRunLoopRunSpecific + 446 (CoreFoundation + 521801) [0x7fff20439649]
  52  __CFRunLoopDoObservers + 549 (CoreFoundation + 527405) [0x7fff2043ac2d]
  52  __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23 (CoreFoundation + 527773) [0x7fff2043ad9d]
  52  ??? (libqcocoa.dylib + 238217) [0x10862a289]
  52  QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 809 (QtCore + 2071353) [0x103ee8b39]
  52  QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212 (QtCore + 2066420) [0x103ee77f4]
  52  sipQApplication::notify(QObject*, QEvent*) + 114 (QtWidgets.so + 157538) [0x106c46762]
  52  QApplication::notify(QObject*, QEvent*) + 497 (QtWidgets + 74785) [0x10717b421]
  52  QApplicationPrivate::notify_helper(QObject*, QEvent*) + 266 (QtWidgets + 69626) [0x107179ffa]
  52  QObject::event(QEvent*) + 943 (QtCore + 2242911) [0x103f1295f]
  52  PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) + 58 (QtCore.so + 1178058) [0x103b5b9ca]
  52  PyQtSlotProxy::unislot(void**) + 88 (QtCore.so + 1178200) [0x103b5ba58]
  52  PyQtSlot::invoke(void**, _object*, void*, bool) const + 374 (QtCore.so + 1175302) [0x103b5af06]
  52  PyQtSlot::call(_object*, _object*) const + 40 (QtCore.so + 1175544) [0x103b5aff8]
  52  PyObject_Call + 101 (Python + 42377) [0x103134589]
  52  _PyObject_Call_Prepend + 156 (Python + 43051) [0x10313482b]
  52  _PyObject_FastCallDict + 196 (Python + 42760) [0x103134708]
  52  _PyFunction_FastCall + 121 (Python + 696809) [0x1031d41e9]
  52  _PyEval_EvalFrameDefault + 1659 (Python + 661025) [0x1031cb621]
  52  call_function + 450 (Python + 692413) [0x1031d30bd]
  52  _PyFunction_FastCall + 121 (Python + 696809) [0x1031d41e9]
  52  _PyEval_EvalFrameDefault + 1659 (Python + 661025) [0x1031cb621]
  52  call_function + 450 (Python + 692413) [0x1031d30bd]
  52  _PyFunction_FastCall + 121 (Python + 696809) [0x1031d41e9]
  52  _PyEval_EvalFrameDefault + 1659 (Python + 661025) [0x1031cb621]
  52  call_function + 450 (Python + 692413) [0x1031d30bd]
  52  fast_function + 218 (Python + 696137) [0x1031d3f49]
  52  _PyEval_EvalCodeWithName + 1747 (Python + 694374) [0x1031d3866]
  52  _PyEval_EvalFrameDefault + 1659 (Python + 661025) [0x1031cb621]
  52  call_function + 491 (Python + 692454) [0x1031d30e6]
  52  _PyCFunction_FastCallDict + 463 (Python + 274734) [0x10316d12e]
  52  meth_QEventLoop_exec_(_object*, _object*, _object*) + 194 (QtCore.so + 259906) [0x103a7b742]
  52  QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431 (QtCore + 2050191) [0x103ee388f]
  52  ??? (libqcocoa.dylib + 235103) [0x10862965f]
  52  -[NSApplication run] + 586 (AppKit + 195546) [0x7fff22c3dbda]
  52  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366 (AppKit + 251723) [0x7fff22c4b74b]
  52  _DPSNextEvent + 883 (AppKit + 257925) [0x7fff22c4cf85]
  52  _BlockUntilNextEventMatchingListInModeWithFilter + 64 (HIToolbox + 199407) [0x7fff2869daef]
  52  ReceiveNextEventCommon + 283 (HIToolbox + 199714) [0x7fff2869dc22]
  52  RunCurrentEventLoopInMode + 292 (HIToolbox + 200656) [0x7fff2869dfd0]
  52  CFRunLoopRunSpecific + 563 (CoreFoundation + 521918) [0x7fff204396be]
  52  __CFRunLoopRun + 838 (CoreFoundation + 524509) [0x7fff2043a0dd]
  52  __CFRunLoopDoObservers + 549 (CoreFoundation + 527405) [0x7fff2043ac2d]
  52  __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23 (CoreFoundation + 527773) [0x7fff2043ad9d]
  52  ___NSRunLoopObserverCreateWithHandler_block_invoke + 41 (AppKit + 9493774) [0x7fff2351bd0e]
  52  __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 285 (AppKit + 1849803) [0x7fff22dd19cb]
  52  CA::Transaction::commit() + 783 (QuartzCore + 8369) [0x7fff26bba0b1]
  52  CA::Context::commit_transaction(CA::Transaction*, double, double*) + 517 (QuartzCore + 1434691) [0x7fff26d16443]
  51  CA::Layer::display_if_needed(CA::Transaction*) + 874 (QuartzCore + 149328) [0x7fff26bdc750]
  37  -[_NSViewBackingLayer display] + 555 (AppKit + 1152888) [0x7fff22d27778]
  37  -[_NSBackingLayer display] + 475 (AppKit + 1763233) [0x7fff22dbc7a1]
  37  -[CALayer display] + 183 (QuartzCore + 151202) [0x7fff26bdcea2]
  36  ??? (libqcocoa.dylib + 174971) [0x10861ab7b]
  32  ??? (libqcocoa.dylib + 139916) [0x10861228c]
  32  void QWindowSystemInterface::handleExposeEvent<QWindowSystemInterface::SynchronousDelivery>(QWindow*, QRegion const&) + 178 (QtGui + 138402) [0x10637cca2]
  32  bool QWindowSystemInterfacePrivate::handleWindowSystemEvent<QWindowSystemInterface::SynchronousDelivery>(QWindowSystemInterfacePrivate::WindowSystemEvent*) + 115 (QtGui + 108003) [0x1063755e3]
  32  QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) + 306 (QtGui + 255074) [0x106399462]
  32  QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212 (QtCore + 2066420) [0x103ee77f4]
  31  sipQApplication::notify(QObject*, QEvent*) + 114 (QtWidgets.so + 157538) [0x106c46762]
  31  QApplication::notify(QObject*, QEvent*) + 497 (QtWidgets + 74785) [0x10717b421]
  31  QApplicationPrivate::notify_helper(QObject*, QEvent*) + 266 (QtWidgets + 69626) [0x107179ffa]
  31  ??? (QtWidgets + 430166) [0x1071d2056]
  31  ??? (QtWidgets + 442468) [0x1071d5064]
  31  ??? (QtWidgets + 117443) [0x107185ac3]
  31  ??? (QtWidgets + 118978) [0x1071860c2]
  30  QBackingStore::flush(QRegion const&, QWindow*, QPoint const&) + 1218 (QtGui + 2003874) [0x1065443a2]
  11  ??? (libqcocoa.dylib + 96941) [0x108607aad]
  7   ??? (libqcocoa.dylib + 98356) [0x108608034]
  7   -[NSInvocation invoke] + 303 (CoreFoundation + 410624) [0x7fff2041e400]
  7   __invoking___ + 140 (CoreFoundation + 410972) [0x7fff2041e55c]
  5   -[NSWindow _maskRoundedBottomCorners:] + 194 (AppKit + 3876440) [0x7fff22fc0658]
  4   -[NSThemeFrame _maskCorners:clipRect:] + 230 (AppKit + 3208674) [0x7fff22f1d5e2]
  4   -[NSAppearance _drawInRect:context:options:] + 111 (AppKit + 1729446) [0x7fff22db43a6]
  4   -[NSCompositeAppearance _callCoreUIWithBlock:options:requireBezelTintColor:] + 386 (AppKit + 301764) [0x7fff22c57ac4]
  3   __44-[NSAppearance _drawInRect:context:options:]_block_invoke + 83 (AppKit + 1729544) [0x7fff22db4408]
  3   CUIDraw + 172 (CoreUI + 95830) [0x7fff26ed3656]
  2   CUIRenderer::Draw(CGRect, CGContext*, __CFDictionary const*, __CFDictionary const**) + 1777 (CoreUI + 97655) [0x7fff26ed3d77]
  1   CUICoreThemeRenderer::DrawWindowBottomBar(CUIDescriptor const*) + 2408 (CoreUI + 210134) [0x7fff26eef4d6]
  1   CGContextRestoreGState + 32 (CoreGraphics + 174993) [0x7fff24f2fb91]
  1   CGGStackRestore + 5 (CoreGraphics + 175030) [0x7fff24f2fbb6]


Also really weird about gns3 version it detects, I am 100% sure it is 2.2.16.

/Applications/GNS3.app/Contents/MacOS/gns3 --version
2.2.16

**Comment by tao-lian** [comment]
Upgrade to 20B28 yesterday, GNS 3 still cannot load. 

TBH, there is also big issue with VMWare Fusion 12 cannot do nested virutalisation. It does feel like it will be some time before GNS 3 + VM can work properly

**Comment by grossmj** [comment]
Thanks for the info. Also, we will need xcode support for 11.0 on CircleCI https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions (this is where we build our macOS app).

**Comment by tao-lian** [comment]
> Thanks for the info. Also, we will need xcode support for 11.0 on CircleCI https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions (this is where we build our macOS app).

If you have nightly build to test on Big Sur, I am more than happy to help. But as I mentioned above, neither VMware 12 nor virtualbox can run properly on Big Sur, I believe they have more problems than GNS3 ^_^

**Comment by Vardiak** [comment]
@tao-lian what I have done is install GNS3 GUI on a Lubuntu VM on VirtualBox & another a GNS3 VM side by side. Then, I connect to my GNS3 VM from my Lubuntu VM as if it was a distant server.

**Comment by twagener** [comment]
It seems to be a bug in pyqt5 and they have filed the bug (Some rumors that 5.13.1 is still working). Many other projects using python fixed it already. I found a dirty workaround to get the sources running on Mac by adding this 3 lines to the top of the main() function.

```
import matplotlib
import matplotlib.pyplot as plt


matplotlib.use('TkAgg')
```

I dont't know why, but it's working. Maybe there are some dependencies or hooks imported with these lines.

Hopefully it will be fixed soon.

**Comment by twagener** [comment]
It's running with this PyQT Version

```pip install pyqt5-sip==4.19.19 pyqt5==5.12.1```

a quick fix build would be great!

**Comment by thcorre** [comment]
> Upgrade to 20B28 yesterday, GNS 3 still cannot load.
> 
> TBH, there is also big issue with VMWare Fusion 12 cannot do nested virutalisation. It does feel like it will be some time before GNS 3 + VM can work properly

It seems resolved since Fusion 12.1.0 (my GNS3 VM is server is launching while having enable VT-x support). 
See release notes:
https://docs.vmware.com/en/VMware-Fusion/12.1.0/rn/VMware-Fusion-1210-Release-Notes.html

And below extract:
"Nested virtualization is now supported on the CPU models without the VMCS shadowing feature."

**Comment by tao-lian** [comment]
> > Upgrade to 20B28 yesterday, GNS 3 still cannot load.
> > TBH, there is also big issue with VMWare Fusion 12 cannot do nested virtualization. It does feel like it will be some time before GNS 3 + VM can work properly
> 
> It seems resolved since Fusion 12.1.0 (my GNS3 VM is launching while having enabled VT-x support).
> See release notes:
> https://docs.vmware.com/en/VMware-Fusion/12.1.0/rn/VMware-Fusion-1210-Release-Notes.html
> 
> And below extract:
> "Nested virtualization is now supported on the CPU models without the VMCS shadowing feature."

They fixed it in 12.1 indeed! However, there is another very annoying issue is NAT does not work for me!
https://communities.vmware.com/t5/VMware-Fusion-Discussions/macOS-Big-Sur-Fusion-12-NAT-no-internet-connection/td-p/2809034

I know I can bridge the network, but as I remember GNS3 not recommanded to bridge to a WIFI NIC. I havent tried recently, but I remember it was very stable.

**Comment by grossmj** [comment]
@twagener 

> Many other projects using python fixed it already

Do you know which ones? Thanks :+1:

**Comment by twagener** [comment]
> @twagener
> 
> > Many other projects using python fixed it already
> 
> Do you know which ones? Thanks 👍

Mine for example. You need the right pyqt versions. I used these `pip install pyqt5-sip==4.19.19 pyqt5==5.12.1`

**Comment by grossmj** [comment]
> Mine for example. You need the right pyqt versions. I used these pip install pyqt5-sip==4.19.19 pyqt5==5.12.1

Unfortunately, it is not easy for us to upgrade because freezing app is a nightmare.

However, I found a workaround. With GNS3.app in `/Applications`, open a Terminal and type this:

`QT_MAC_WANTS_LAYER=1 open -a GNS3.app`

![Screenshot from 2020-11-30 19-44-18](https://user-images.githubusercontent.com/4752614/100590572-7ba2ed80-3344-11eb-8fad-6973e57eb7c7.png)

**Comment by grossmj** [comment]
Looks like all I need to do is to add `os.environ['QT_MAC_WANTS_LAYER'] = '1'` in our code. This will be done in version 2.2.17

**Comment by jnatschev** [comment]
i'd like to share that i have managed to get GNS3 GUI 2.2.16, GNS3 Server 2.2.16, and GNS3 VM 2.2.16 to launch and give me the GUI and connect to the server and VM. the way i did it is to use python 3.7 (the latest) use pip to install gns3 gui and gns3 server on MacOS Big Sur. then:
1. start GNS3 VM on VMWare Fusion
2. python -m gns3server (no errors)
3. python -m gns3 (no errors)

This is as far as i got. need to download a csr1000v image to test further. i'm encouraged so far. 

Cheers,
John

**Comment by grossmj** [comment]
@jnatschev thanks for sharing :+1:

**Comment by jnatschev** [comment]
further update.

i downloaded a csr1000v image, 16.12.04a, modified the gns3 csr1000v appliance file to include this version of the csr1000v and have successfully added two csr1000v routers into a topology, configured to do bgp between them.

i can say job done. their working fine.

so:
macos big sur
vmware fusion 12.1.0
gns3 gui 2.2.16
gns3 server 2.2.16
gns3 vm 2.2.16

also, be aware, the python installation is via anaconda (conda). i created a specific "environment", named gns3-3.7, for gns3. pip install didn't seem to install sip and PyQt. so i did a conda install -n gns3-3.7 PyQt. this installed the needed PyQt packages and sip. next i'll try with a new conda environment using the packages from the conda channel conda-forge.

fingers crossed

**Comment by matthieugouel** [comment]
For today, I succeeded to launch GNS3 from command line with : 
```
pip install pyqt5-sip==4.19.19 pyqt5==5.12.1
export QT_MAC_WANTS_LAYER=1
open -a GNS3
```

**Comment by grossmj** [comment]
Our last nightly build should work on Big Sur: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2020-12-01/2.2/GNS3-2.2.17dev1.dmg/download

**Comment by grossmj** [comment]
I consider this issue to be solved. Next version, 2.2.17 will work on macOS Big Sur. Thanks to everyone who helped and please comment back if you find issues running the latest nightly build.

**Comment by henri9813** [comment]
Hello,

Do you know when this will be released ? 

Best regards

**Comment by grossmj** [comment]
Today or tomorrow.
