### ISSUE TITLE
"reload" VM doesn't reload his GNS3 config

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3038]
Hi

(I don't know if it is a bug or an enhancement)

I have a QEmu VM with 200M of RAM (for example).
I start it.

With the GNS3 config, i increase the VM's RAM to 300M.

I click on the button "Reload".
The VM's OS reboot.
But the VM thinks always that it has 200M.

**Comment by b-ehlers** [comment]
On QEMU VMs a reload is similar to doing a RESET on a physical device. It's still the old QEMU process with it's old parameters. If you want a new QEMU VM with updated parameters you have to stop, then start the VM.

So I would categorize this as a limitation, not a bug.

**Comment by Raizo62** [comment]
> On QEMU VMs a reload is similar to doing a RESET on a physical device. It's still the old QEMU process with it's old parameters. If you want a new QEMU VM with updated parameters you have to stop, then start the VM.

I feared that was the reason. This is why I did not claim that it is a bug.

But, often, my students do the error to click on reload instead Stop/Start

Perhaps to use a boolean to detect a change of the config. If it is true, the button "reload" does a Stop/Start

**Comment by grossmj** [comment]
> Perhaps to use a boolean to detect a change of the config. If it is true, the button "reload" does a Stop/Start

Done :+1:

**Comment by vint66** [comment]
Hi Jeremy,

This commit seems like caused error below.
Issue happens if you make any change for project config (for example change scene height) if this project has QEMU node with port connection.

2020-09-29 17:25:03 ERROR route.py:242 Uncaught exception detected: <class 'TypeError'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/local/lib/python3.8/dist-packages/gns3server/handlers/api/compute/project_handler.py", line 98, in update_project
    await project.update(
  File "/usr/local/lib/python3.8/dist-packages/gns3server/compute/project.py", line 305, in update
    await node.update()
TypeError: update() missing 2 required positional arguments: 'name' and 'value'


node.update() for qemu expecting 2 arguments.
