### ISSUE TITLE
Curved connection links between nodes

### ISSUE THREAD

**Issue by g1augusto** [GNS3/gns3-gui#3057]
Hi Everyone, Jeremy,

This is a simple one but I believe quite effective: 

Can we have the option to define a non linear path for link connections between nodes?

Reason for this is that when a topology grows in size it becomes difficult to read properly place together all nodes with overlapping link lines.

Thank you!

**Comment by cristian-ciobanu** [comment]
There is already such an enhancement request opened for this: https://github.com/GNS3/gns3-gui/issues/2303

Also this one: https://github.com/GNS3/gns3-gui/issues/2608

You can close this one as it is a duplicate.

**Comment by aksplease** [comment]
hi Cristian-ciobanu,

will we see this Drawing enhancement soon in gns3 ?really its a needed feature in gns3 

![Feature enhancement](https://user-images.githubusercontent.com/11521667/94337696-32fc4a80-000a-11eb-8a5a-e7a8a00a103f.PNG)

**Comment by grossmj** [comment]
Unfortunately we are more focusing on the back-end of GNS3 at the moment (user management, authentication and rights etc.) so this will have to wait. I am closing this since we already have issues opened for it.

**Comment by AbdelbakiBoukerche** [comment]
I managed implement this! although it's not perfect (roughly 2 hours of reading the code and trying to make sense of it) and as you can see the link status indicator are way off, I honestly can't think of a way to put the back in place (since the link is no longer linear) I have to read some search some math formulas to come up with new points to put the link status indicator!

![01](https://user-images.githubusercontent.com/46383961/182684411-d8e30c26-5ec8-43a1-bc2d-c86fc7d35e41.png)
![02](https://user-images.githubusercontent.com/46383961/182684414-bc90f3c5-79cb-4988-971b-e7941aaa63c0.png)

**Comment by aksplease** [comment]
Dear Jeremy Grossmann,

is this logic of AbdelbakiBoukerche can work for GNS#3 with proper development of code  ?

regards
