### ISSUE TITLE
gns3-gui does not support C locale

### ISSUE THREAD

**Issue by AdrianSimionov** [GNS3/gns3-gui#310]
asimionov@Desktop-PC:~/git/gns3-gui$ gns3
GNS3 GUI version 1.3.3dev1
Copyright (c) 2007-2015 GNS3 Technologies Inc.
could not find a default locale, switching to C.UTF-8...
could not switch to the C.UTF-8 locale: unsupported locale setting

Sorry if it "by design", I just want to be sure you know about it.

**Comment by grossmj** [comment]
Hi Adrian,

Yep this is by design, the idea is to prevent UnicodeEncodeError with unicode paths when using standard library I/O operation methods (e.g. os.stat() or os.path.*) which rely on the system or user locale.

More information can be found there: http://seasonofcode.com/posts/unicode-i-o-and-locales-in-python.html or there: http://robjwells.com/post/61198832297/get-your-us-ascii-out-of-my-face

Hope this makes sense.

Regards,

**Comment by AdrianSimionov** [comment]
Thanks for the fast reply, I will close it for now, maybe it will help others in the future, I just changed my locale and it works.
