### ISSUE TITLE
Suspend link does not work between hubs

### ISSUE THREAD

**Issue by luizluca** [GNS3/gns3-gui#3120]
**Describe the bug**
When I suspend a link, it looks like the cable is disconnected as machines detect it.
However, when I suspend the link between two hubs, it looks like they do not care about that state
and keep forwarding packets.

**GNS3 version and operating system (please complete the following information):**
 - OS: OpenSUSE Tumbleweed
 - GNS3 2.2.17
 - Gui on OpenSUSE Tumbleweed, backend on GNS3 VM virtualbox

**To Reproduce**
1. Connect 2 machines through 2 hubs.
2. if I only disable the link between one hub and a machine, it stops the ping as expected
3. if I only disable the link between the two hubs, it keeps working

**Additional context**
It would be better to have this feature working. However, it is not feasible, it should gives a warning just like it already happens with filters, or even disable/hide both popup menu items (filter,suspend) for unsupported links.

**Comment by grossmj** [comment]
I replicated the problem, this is the same with the simple Ethernet switch we provide.

This is due to a limitation since we use Dynamips to run these devices, including their links. Other devices like Qemu VM and Docker use uBridge which allow us to suspend links. Unfortunately, Dynamips does not provide a way to suspend links.

We hope to solve this when we migrate to a Linux bridge network backend in the future.

**Comment by luizluca** [comment]
Gns3 could, behind the scenes, temporary remove the link and readd it when the link is resume. The effect is the same.
