### ISSUE TITLE
wrong cable alignment on custom icons

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#3142]
Community link: https://gns3.com/community/support/wrong-cable-alignment-on-custom-icons

**Comment by b-ehlers** [comment]
This issue is present only in the WebUI, the GNS3 GUI works fine. So it's more an issue for the [WebUI](https://github.com/GNS3/gns3-web-ui). It looks similar to https://github.com/GNS3/gns3-web-ui/issues/1019.

When I change the size of the 128.svg from 300 to 70 it looks fine both in the GUI and the WebUI, here the diff to change the size:

```
--- 128.svg	2021-03-03 19:06:16.248297583 +0100
+++ 128_70.svg	2021-03-03 19:04:19.549322857 +0100
@@ -12,8 +12,8 @@
    xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
    version="1.1"
    id="svg2"
-   width="300"
-   height="300"
+   width="70"
+   height="70"
    viewBox="0 0 300 300"
    sodipodi:docname="128.svg"
    inkscape:version="0.92.4 (5da689c313, 2019-01-14)">
```

**Comment by piotrpekala7** [comment]
@grossmj 
problem is visible in web UI, reason described here https://github.com/GNS3/gns3-web-ui/issues/1047
