### ISSUE TITLE
Consolidation of "Server" settings GUI in Edit-Preferences

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-gui#3199]
**Is your feature request related to a problem? Please describe.**
Currently, the  configuration and display of the various server types (Local, Remote Main, VM, Remote) is spread across multiple panels/tabs. This is not the most intuitive for new users that have never worked with GNS3 nor familiar with the architecture.

**Describe the solution you'd like**
Consolidating ALL servers in to a table, and having a column to denote what type of server they are, in addition to some clear indication of which server is the controller (perhaps another column or simply and "*" next to the server name. Then simple "Add", "Edit" and "Delete" buttons. From there, a simplified wizard could be developed to handle adding servers of different types.

Example:

Server Name:      Controller:     Server Type:     Server IP:

Server 1                Yes               Local               192.168.1.2
Server 2                No                Remote            192.168.1.3

**Comment by grossmj** [comment]
I have simplified the settings for version 3.0

Now you can only configure a controller (which can be only be local on Linux since we are dropping server support for Windows and probably for macOS)

![Screenshot from 2021-12-27 17-24-37](https://user-images.githubusercontent.com/4752614/147443755-3760a52d-ce69-43ba-8ba3-938f399d10c3.png)

and if you need extra compute power, you can add remote computes in a second tab.

![Screenshot from 2021-12-27 17-24-59](https://user-images.githubusercontent.com/4752614/147443744-2b065472-6b10-4ed8-a7e1-25e4bcc3a262.png)

That's pretty much it.

I think that will solve this issue however please let me know your thoughts if you think of something that could be even more simplified.
