### ISSUE TITLE
Mac client attempts to connect to vmware VM with wrong IP address

### ISSUE THREAD

**Issue by cognitiaclaeves** [GNS3/gns3-gui#3200]
**Describe the bug**
New install on Mac. VMware vm clearly getting .2 ip address, but Mac client expects to connect to .1.

**GNS3 version and operating system (please complete the following information):**
 - OS: Mac BigSur 11.4
 - GNS3 version 2.2.22
 - Vmware Fusion GNS3 VM (VM file upgraded by vmware)

**To Reproduce**
I was trying to follow a video. But the installation wasn't without stops and trying to figure out what happened to get it on the right track. So, I don't have a concrete set of steps to reproduce the behavior.
1. Install GNS3 on Mac
2. Enable local server (don't know if this needs to happen, but not able to choose VM settings until I do)
3. Import GNS3 vmware virtual machine file into VMware Fusion Player Version 12.1.2 (17964953)
4. Allow VMware Fusion to upgrade VM to latest version
5. Look for errors of GNS3 not being able to connect (see screenshot)

** Screenshot **

VM info:
<img width="1682" alt="Screen Shot 2021-06-21 at 11 15 34 AM" src="https://user-images.githubusercontent.com/8933161/122796717-534cf300-d284-11eb-8a0a-f2d77527ec79.png">

Options for local server:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/8933161/122797006-9e670600-d284-11eb-8b78-57ba7ca37bc8.png">

**Comment by jnatschev** [comment]
Hey.

From memory, the GNS3 Server will attach to .1 in order to communicate with the GNS3 VM on .2.

On my Mac this is the behaviour. My setup is as follows:
VMware Fusion has the following Networks:
vmnet2, vmnet3, …, vmet12.
GNS3 VM network adaptor 1 is associated with vmnet10
GNS3 VM network adaptor 2 is associated with Shared with my Mac (NAT)

GNS3 GUI Preferences:
Server -> Main Server -> Host binding: 10.0.10.1 (This is the IP address of the vmnet10 network)

GNS3 VM eth0: 10.0.10.2

Because I am using a vmnet (vmnet10) other than Private to my Mac, the order of execution needs to be:
- Start GNS3 VM manually and wait for the GNS3 VM to have completely started
- Start the GNS3 GUI

Ensure in your GNS3 GUI Preferences - GNS3 VM:
Enable GNS3 VM is “ticked”
Virtualisation Engine: VMware Fusion
Action when closing GNS3: keep the GNS3 VM running

Once you’ve finished using GNS3 GUI, then close it first. Once it has closed, shutdown the the GNS3 VM.

If you use Private to my Mac for network adaptor 1 on the GNS3 VM you don’t need to worry about any of it. I have chosen to use my defined vmnet, so I do it this way.

Hope this helps.




Cheers,
John Natschev
18 Cobham Road
Mitcham
Victoria 3132
Australia
+61438533492
