### ISSUE TITLE
"No Qt platform plugin could be initialized..."

### ISSUE THREAD

**Issue by nowheremanhere** [GNS3/gns3-gui#3213]
Hope I'm in the right spot here.  Apologies if not.

I'm attempting to install GNS3 version GNS3-2.2.22 as a client on Windows 10 to remotely access a GNS3 server in the Azure cloud.  

After installation, on first launch of the client GNS3, I configure GNS3 for remote server. After configuration I launch the app and I get the message "No Qt platform plugin could be initialized..."

If I acknowledge the error and launch GNS3 I immediately get error message "Websocket notification stream error: QWebSocketPrivate::processHandshake: Unhandled https status code: 404(Not Found)."  And the app freezes up.

![error](https://user-images.githubusercontent.com/63795903/127736440-3857b973-d8e7-45e5-8506-36841250ca11.jpg)
![error2](https://user-images.githubusercontent.com/63795903/127736442-a7358bd6-d560-45a4-b9de-c5a724062ef1.jpg)
thanks for any guidance you might be able to provide...

**Comment by josephmhiggins** [comment]
We have to wait until nowheremanhere responds on https://gns3.com/community/featured/no-qt-platform-plugin-could-be-initialized to see if this is resolved.

Because I believe the true error was masked in the gns3_gui.log file:
I can not tell if there is an order of operation error in the gns3 code, or
if nowheremanhere just happen to hit the Ctrl-C on his keyboard before gns3 could post the true error message

I am not a programmer nowheremanhere, but I think that SIGBREAK that occurred within 2 minutes of a pause in the
gns3_server.log is you hitting the CTRL-C on your keyboard. There are all kinds of rules that developers have to follow when someone hits a CTRL-C in a program. I do not anything about any of those rules. Maybe they broke a rule, or maybe they did not break a rule. That's up to them to decide.

**Comment by josephmhiggins** [comment]
Oh.... maybe you went into task manager and clicked on end task....?? That's why gns3 faq for new yours has item 4.

   1. Topology screenshot (interfaces, IP addresses...)
   2. OS version
   3. GNS3 version
   4. Action/steps performed
   5. Expected results / unexpected results (errors)
   6. Appliance configurations files attached

**Comment by mangkoran** [comment]
@josephmhiggins where can I find `gns3_gui.log` file? I have similar issue. I'm in Windows 11 22000.120. I cannot run `gns3-gui`. At first I can run it. But after I uninstall and install `gns3` back, somehow I cannot run `gns3-gui`. It only show `cmd` window and then quitted without outputting anything.

**Comment by mangkoran** [comment]
Seems it fixed by installing package from [here](https://github.com/GNS3/gns3-gui/issues/3214#issuecomment-894953722). Although my issue seems different from OP one.

**Comment by grossmj** [comment]
@nowheremanhere have you managed to run the GUI?
