### ISSUE TITLE
The locally opened shared virtual machine "GNS3 VM.vmx" is not allowed.

### ISSUE THREAD

**Issue by laokong4628** [GNS3/gns3-gui#3238]
GNS3 version and operating system:

- OS:  Windows 10
- GNS3 version 2.2.25
- no GNS3 VM or remote server

Describe the bug:

When i install GNS3.VM.VMware.Workstation.2.2.25 to my VMware® Workstation 16 Pro, have an error occurred that is "The locally opened shared virtual machine "GNS3 VM.vmx" is not allowed."

To Reproduce:

1. Open VMware software then import GNS3 VM.ova file.
2. When the import is about to end, This error occurred.

I don't known the reason, Why? Has anyone encountered a similar situation like me?
Please help me, thanks...

Screenshots:

![image](https://user-images.githubusercontent.com/57978274/134766812-40c791a3-9057-45f3-9f7e-e5189b5a0e3d.png)

**Comment by josephmhiggins** [comment]
Many people are reporting this with their NON-GNS3 shared VMs. I do not know if shared vms are supported in vmware workstation pro 16.

https://www.google.com/search?q=site.vmware.com+vmx+is+not+allowed&rlz=1C1CHBD_enUS910US910&oq=site.vmware.com+vmx+is+not+allowed&aqs=chrome..69i57j33i299l2.15774j0j7&sourceid=chrome&ie=UTF-8

https://docs.vmware.com/en/VMware-Workstation-Pro/15.0/com.vmware.ws.using.doc/GUID-32D21846-E12C-40A4-A02F-E9315B0AE8FE.html

Here is your 16.0 documentation

https://docs.vmware.com/en/VMware-Workstation-Pro/15.0/com.vmware.ws.using.doc/GUID-32D21846-E12C-40A4-A02F-E9315B0AE8FE.html

**Comment by josephmhiggins** [comment]
This is definitely not a gns3 bug. I suspect this has something to do with how Microsoft wants their operating systems to be used as a system to host hypervisors. The licensing was changed in either Windows 2012 server or Windows 2016 server. Microsoft's licensing is complicated. The only thing I know at this time is that Microsoft wants to make money. Unfortunately, this will have to be investigated because some GNS3 users may use VMware Workstation Pro on a Windows 10 host remotely. But I do not believe that this is a discussion that should directly "bring in", or directlly "involve" the gns3 developers. This should be investigated by the GNS3 community. But the problem with relying on the GNS3 community is that this issue is very complicated and involves money. I did not know about this issue until your post. So, I just do not know.

**Comment by grossmj** [comment]
I haven't got any issue importing the GNS3 VM OVA in VMware Workstation Pro 16

![Screenshot from 2021-10-08 19-48-16](https://user-images.githubusercontent.com/4752614/136531391-af60175d-9491-4144-b2d8-77967cb3eb15.png)

Regarding shared VMs, they aren't supported anymore, see https://docs.vmware.com/en/VMware-Workstation-Pro/16.1.0/rn/VMware-Workstation-1610-Pro-Release-Notes.html

> Deprecation of the Shared virtual machine feature
The Shared virtual machine feature (VMware Workstation as server) is being deprecated. It will remain in its present form for the remainder of the VMware Workstation 16 product life. This feature will be not available in a future release.

Not sure what is wrong on your side, maybe try to upgrade VMware Workstation Pro 16 to the latest available minor version?
