### ISSUE TITLE
upgrade issue

### ISSUE THREAD

**Issue by azeemkm20** [GNS3/gns3-gui#3243]
after upgrading gns3 VM to 2.2.26 its not show 2.2.26 instead of its showing 2.2.5 
![gns3 isse](https://user-images.githubusercontent.com/31308449/136651666-e6c26eeb-faa4-46af-81ca-77f409ada40e.PNG)

**Comment by grossmj** [comment]
Same as https://github.com/GNS3/gns3-server/issues/1983

Looks like the problem is the GNS3 VM you used is based on Ubuntu Bionic (18.04 LTS) while the latest versions of the GNS3 VM are based on Ubuntu Focal (20.04 LTS).

I have changed the upgrade script. Please try to upgrade again and let me know if it works for you.

**Comment by grossmj** [comment]
@azeemkm20 @mortiz-code have you tried to upgrade again?
