### ISSUE TITLE
Add "Copy" button to every template group in the "Preferences" dialog

### ISSUE THREAD

**Issue by andrei-korshikov** [GNS3/gns3-gui#3254]
**Problem description**
In the **Preferences** dialog some template groups (**"IOS Routers", "IOU Devices", "Qemu VMs", "Docker containers"**) have "Copy" button, and others don't. This inconsistency is a bit frustrating;)

**Describe the solution you'd like**
Add "Copy" button to all template groups.

**Screenshots (examples)**
**"Qemu VM templates"** section has the "Copy" button:
![image](https://user-images.githubusercontent.com/15959858/138555190-12045c7a-2649-4ff5-8678-e8946af6cc4e.png)
**"Cloud node templates"** section does not have the "Copy" button:
![image](https://user-images.githubusercontent.com/15959858/138555225-bda42500-7730-461c-a776-9ad5a83fa5be.png)

**Comment by grossmj** [comment]
> Add "Copy" button to all template groups.

The reason behind this is that it doesn't make sense to copy VirtualBox and VMware templates since they are tied to VMs inside these software. For the other templates, we could eventually add a copy button but the built-in and VPCS templates have very few settings, most have only a name, so I believe it's not that important that you cannot copy them.
