### ISSUE TITLE
Cannot communicate with the GNS3 VM

### ISSUE THREAD

**Issue by aksplease** [GNS3/gns3-gui#3297]
**Before you start**
Please open an issue only if you suspect there is a bug or any problem with GNS3. Go to https://gns3.com/community for any other questions or for requesting help with GNS3.

You may also post this issue directly on the GNS3 server repository if you know the bug comes from the server: https://github.com/GNS3/gns3-server/issues/new

**Describe the bug**
Please provide a clear and detailed description of what the bug is.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows-11
 - GNS3 version [2.2.29 and previous as well ]
 - Any use of the GNS3 VM on Vmware WS-16.2.2 also tested on lower version 
![Brdgeport Error](https://user-images.githubusercontent.com/11521667/155203761-14cb9903-4b44-440d-b90e-6ec8d80b9a9f.png)
![bridge Port](https://user-images.githubusercontent.com/11521667/155203767-6e3ebcbf-03e8-4106-b53f-86a063c502b4.png)
![gns3 not connected after bridgeport](https://user-images.githubusercontent.com/11521667/155203772-ee0b030a-2729-46a2-8e30-5d2f5aa4dbaf.png)
![gns3 not connected](https://user-images.githubusercontent.com/11521667/155203775-f1e0411f-e63f-407e-8298-dce5af73cb5c.png)
![vm interface config](https://user-images.githubusercontent.com/11521667/155203777-63521abe-8d39-4e27-8810-02358443865d.png)
![well communicatio under Nat condition](https://user-images.githubusercontent.com/11521667/155203781-10f4479b-d4eb-4fb3-b721-0c487aedab80.png)
![Cloud Conneectivity fine](https://user-images.githubusercontent.com/11521667/155203860-2a3eb86c-5a1b-4c3d-bf08-3f0be46b2cd2.png)
![Firewal stoped ](https://user-images.githubusercontent.com/11521667/155203868-9a732040-fa8d-4d14-bb03-47b0eb16207c.png)
[gns3.txt](https://github.com/GNS3/gns3-gui/files/8119599/gns3.txt)
![Gns3-config-1](https://user-images.githubusercontent.com/11521667/155203874-1dd7b0f8-fa12-4490-a862-72a7f6a0f954.png)
![Gns3-config-2](https://user-images.githubusercontent.com/11521667/155203878-00506639-5ad2-4e1c-a62e-4e9362f4231d.png)
![IOS crash ](https://user-images.githubusercontent.com/11521667/155203879-f82fd178-23bb-4633-851c-d65d8a331b16.png)
![IP-Add-IP-Router command](https://user-images.githubusercontent.com/11521667/155203882-bfb9e4a6-2a46-4c5a-9fa3-4e46af17eb82.png)
![IP-Add-IP-Router-ufw status command](https://user-images.githubusercontent.com/11521667/155203886-ac378dc0-cfe7-4bce-83eb-bab54d609c8a.png)
![ipconfigall-1](https://user-images.githubusercontent.com/11521667/155203887-addba761-acfc-4c66-bc03-09175eccef15.png)
![ipconfigall-2](https://user-images.githubusercontent.com/11521667/155203890-f9a2ac51-700f-48f6-b478-e024f8b8a958.png)
![Screenshot 2022-02-12 162505](https://user-images.githubusercontent.com/11521667/155203943-a5f6f06b-9d76-47dc-9b49-6ec317f45deb.png)
![Vmware Downgrade 15 5](https://user-images.githubusercontent.com/11521667/155203949-2213bce0-92f4-4a0a-9066-585b26e04527.png)

**To Reproduce**

**Screenshots or videos**
If applicable, add screenshots (e.g. of the topology and/or error message) or links to videos to help explain the problem. This will help us a lot to quickly find the bug and fix it.

**Additional context**

For a quite long time I am trying to establish communication  between My Host (Window-11,Vm Ws-16.2,gns3 2.2.29) machine and devices running inside GNS3 VM (Qemu,Dynamips).but not being succeed to do so ,regarding that I had a very good conversation with Mr. Joe. But still the problem remain the same. I am doing all things following David's video but not able to make a proper communication ,can please help me to fix the issue or find out any bug in the software …..

pls find the details of discussion 

https://www.gns3.com/community/discussions/host-machine-not-able-to-connect-from-gns3-qemu-dynamip-device

**Comment by josephmhiggins** [comment]
Oh, I put all the a tremendous amount of info in the dupliate bug report here:
https://github.com/GNS3/gns3-gui/issues/3296

This is a gns3 bug and not a vmware bug based on my added info

**Comment by josephmhiggins** [comment]
So, I do not know how this post will be handled, but I would think it would be easiest to mark 3296 as duplicate because I put a ton of comments and info in that post and this post is cleaner.

So here are the things I see that need to be dealt with
1. routing table generated by gns3 for the the gns3 vm is a Bug
2. someone can start wireshark in the gui, which will be going away soon, by right clicking on the link and wireshark will cause all kinds of errors because ntp is not synchronize - this causes confusion
3. the gns3 vm should post a warning if it can not synchronize with an ntp server within X amount of time
4. the gns3 doctor is super easy to do and does not check if ntp is synchronized. I want everyone to use the gns3 doctor.

Then there is the hidden bug that I was searching for in aksplease's original post:
1. the gns3 vm console shows "eth0 is not configured" which is caused by
2. Error code 31 in windows device manager for vmnet1 and vmnet8 (I think it was "Device not functioning properly) when installing vmware ws pro 16 on windows 10. This took me 8 hours to troubleshoot required a "replace in place" of Windows 10. It was a vmware/windows (not gns3) nasty bug.

So, there is quite a few things going on here.

**Comment by josephmhiggins** [comment]
Note: aksplease has a wireless and wired lan adapter.
His primary choice of using adapter is wireless only.
In troubleshooting the problem, I had him disable the wireless adapter and just use the wired adapter.
However, the problem persisted and the ubuntu documentation says that a wired adapter will be favored over a wireless adapter in the routing table, by default.

I do not know how vmware and gns3 and ubuntu will combine on his situation.
But a disabled adapter by the host operating system should not be added into the gns3 vm routing table.
The powershell get-netadapter command does not require admin privileges, but I know nothing how someone could
figure out how an windows adapter is disabled in python.

**Comment by josephmhiggins** [comment]
Note: In powershell for the Error code 31 in device manager, the adapter does not show "Disabled", but it shows up as "Not Present".  I had never seen that before and it is one of the reasons it took me 8 hours to troubleshoot the problem. Obviously, that situation needs to be dealt with also.

**Comment by josephmhiggins** [comment]
@aksplease,
I found a workaround.
You appear to have left a line of text out when you copy and pasted you "ip route" command.

You left out this line:
default via 192.168.1.128 dev eth0 proto dhcp src 192.168.1.1

or since you kept on making changes, it might have changed to this
default via 192.168.1.129 dev eth0 proto dhcp src 192.168.1.1

The problem should be in your
/etc/netplan/90_gns3vm_static_netcfg.yaml

These lines should need to be deleted in your 90_gns3vm_static_netcfg.yaml
      gateway4: 192.168.15.1
      nameservers:
          addresses: [8.8.8.8, 8.8.4.4]

Post back in and the contents of you /etc/netplan like this - **from prompt to prompt** - i need to see both prompts

root@gns3vm:/etc/netplan# ls -al

OUTPUT OMITTED

root@gns3vm:/etc/netplan# 

I did an OUTPUT OMITTED because I spent 5 hours trying to figure this out.
My gns3 vm is ubuntu 18.04 and we need to verify your gns3 vm ubuntu version first.

**Comment by josephmhiggins** [comment]
@aksplease,
In short, I broke my gns3 on December 29, 2021.
My problem has nothing to do with your problem.

Today, I wholesale deleted my gns3 2.2.21 - all my vmdisks in
%homepath%\Documents\Virtual Machines\GNS3 VM 

I removed the GNS3 VM from VMware ws pro.
I downloaded GNS3 VM 2.2.29.
I unzipped it and renamed GNS3 VM.ova to GNS3 VM 2.2.29.ova

I made a directory in %homepath%\Documents\Virtual Machines
and named it GNS3 VM 2.2.29.ova

In ws pro, I just imported it.
I had to go back to gns3 and change in edit - preferences - gns3 vm - port from 3080 to 80, because
when I started the GNS3 VM it said it was listening on port 80.

Then I had to install the gns3-all-in-one for gns 2.2.29

And...."everything works".

So you are back to your wireless adapter/lan adapter and your introduction of vmnet3

Prompt to prompt my routing table looks like this:
gns3@gns3vm:~$ ip route
default via 192.168.234.2 dev eth1 proto dhcp src 192.168.234.130 metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.15.0/24 dev eth0 proto kernel scope link src 192.168.15.131 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 
192.168.234.0/24 dev eth1 proto kernel scope link src 192.168.234.130 
192.168.234.2 dev eth1 proto dhcp scope link src 192.168.234.130 metric 100 
gns3@gns3vm:~$ 

My wireshark works.

Sorry, there is nothing I can do.

**Comment by grossmj** [comment]
@aksplease do you still have the issue?

**Comment by aksplease** [comment]
forget to mention one more thing 
windows default firewall also playing a great role ,the Public network protection feature need to be stopped for the communication to be happen .



    On Wednesday, 27 April, 2022, 08:43:44 pm IST, Ashok Sahoo ***@***.***> wrote:  
 
  Dear Jeremy / team ,


but to communicate the physical network card with gns3 device you have to change the setting in VMware  network  card 0 bridging setting .well i donot think in older gns3 we needed to do so …I don't know whether its a bug or what else please check …    On Wednesday, 27 April, 2022, 08:36:52 pm IST, Ashok Sahoo ***@***.***> wrote:  
 
  hi Jeremy and team 
by following the methods step by step of David I became successfully .GNS3 Talks: Edit the GNS3 VM physical network connection: select network adapter for GNS3 bridging - YouTube

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
GNS3 Talks: Edit the GNS3 VM physical network connection: select network...


 |

 |

 |


i am using windows 11 Enterprise edition with VMware 16.2.3 .


regards Ashok     On Monday, 18 April, 2022, 04:18:27 pm IST, Jeremy Grossmann ***@***.***> wrote:  
 
 


@aksplease do you still have the issue?
