### ISSUE TITLE
New option (Delete All) to contextual menu on "Console"

### ISSUE THREAD

**Issue by pedroflor** [GNS3/gns3-gui#3325]
First of all: Thanks for this amazing software!!!

Would be great if someone can add a new option to the contextual menu for the console that deletes all logs displayed on the console with just one click. Currently it's needed to do:
1) Select All
2) Delete

Here is an image that explains better :)
![image](https://user-images.githubusercontent.com/3332674/165871803-2a9f18a8-7643-4e56-a613-f1fae92e9608.png)

**Comment by pedroflor** [comment]
Just bump up.....

**Comment by josephmhiggins** [comment]
I understand.

Presently, the gns3 developers introduced GNS3 - Help - Export Debug Information (EDI)
I saw a bug in it earlier, but I just checked it now. It's working.
When Export Debug Information is working properly, an experienced GNS3 community member
can upload that zip file to the GNS3 Community board and "it's all over but the crying", because
I can blister through all the files in 5 minutes - and even - almost load up the entire project.
EDI looks to be quite tasty.

So, if EDI is working, then your idea is fine by me - maybe introduce a clear command or something similar.
But if EDI is buggy, then I want GNS3 users to show me a picture of their entire topology - which includes the console.

However, it is not a reasonable expectation for new GNS3 users to paste a picture of their entire topology, or copy text
from their GNS3 console, or to upload an EDI zip file in their GNS3 community post.

So, I do not want GNS3 users to have that option until EDI is considered stable.
I do not know why EDI is working today for me. That's the way it always is..when I know something is broke and I try it again - it magically works.

But yeah, your idea is cool by me.

**Comment by pedroflor** [comment]
Thanks for your time.

**Comment by grossmj** [comment]
> Thanks for your time.

No worries, are you interested to have the "clear" command or a menu entry is a must for you?

**Comment by pedroflor** [comment]
Hey Jeremy!
I can live without it... but for sure, I'll more than happy with the "delete all"  :)

**Comment by grossmj** [comment]
Implemented, will be available in the next release
