### ISSUE TITLE
OSX Big Sur No VMnet interface available, But they DO exist

### ISSUE THREAD

**Issue by jacuinde** [GNS3/gns3-gui#3381]
VMware Fusion 12.2.3
OSX Big Sur 11.6.7
GNS3 2.2.34
GNS3 VM 2.2.34

I create the vmnet 2 to 100 with the steps Preferences -> VMware ->Advanced local settings -> Configure button
Confirmed creation of vmnet 2 to 100 within VMware Fusion networking settings

I create a ubuntu 18 VM in Vmware fusion, i add it to the network topology to a GNS3 VM hosted switch

I try to run the ubuntu 18 VM and it shows the following message:

No VMnet interface available between vmnet2 and vmnet19. Go to preferences VMware / Network / Configure to add more interfaces. 
<img width="467" alt="GNS3 Doctor" src="https://user-images.githubusercontent.com/5535629/188550720-54739a9a-d974-4728-b295-091632a7a25f.png">
[debug.zip](https://github.com/GNS3/gns3-gui/files/9493389/debug.zip)
<img width="1281" alt="GNS3 GUI Error" src="https://user-images.githubusercontent.com/5535629/188550725-1b74a551-92ed-4886-87fa-94b197e0b15e.png">
<img width="571" alt="VMware Fusion Networking" src="https://user-images.githubusercontent.com/5535629/188550726-011744d4-066d-44f1-965e-eaacec965e9b.png">

**Comment by josephmhiggins** [comment]
Umm, yeah, this happened to me in Workstation on Windows 10 about 7 days ago. And I did something to fix it. ...I am thinking that in GNS3 and I think I did:
Preferences - VMware - Advanced local Settings - Reset
and then I think I just did with the default
Vlan2 to Vlan19
Preferences - VMware - Advanced local Settings - Configure
and everything worked

I think I created an "order of operation" error and I did something before I did something else and gns3 was not expecting me to do things in that order.

**Comment by jacuinde** [comment]
I tried your 

> Umm, yeah, this happened to me in Workstation on Windows 10 about 7 days ago. And I did something to fix it. ...I am thinking that in GNS3 and I think I did: Preferences - VMware - Advanced local Settings - Reset and then I think I just did with the default Vlan2 to Vlan19 Preferences - VMware - Advanced local Settings - Configure and everything worked
> 
> I think I created an "order of operation" error and I did something before I did something else and gns3 was not expecting me to do things in that order.

I tried your steps but it still gives me the same error about not finding the VMnet interfaces
<img width="1232" alt="Screen Shot 2022-09-11 at 2 52 38 PM" src="https://user-images.githubusercontent.com/5535629/189550418-190c2c88-c999-4a13-97d5-eada0463789c.png">

**Comment by josephmhiggins** [comment]
No, I know what it is. I originally did not get involved because you are running a Mac and I am running Windows, but I do not think that has anything to do with it.

Thankfully you have a small project.

So, with that project in GNS3 open
1. click on the Ubuntu appliance in the GNS3 topology and delete it
2. close gns3
3. start gns3 and do not load a project, wait until the GNS3 VM turns green
4. do the Reset, Configure technique for VMnet2 to VMnet19 and wait until all the VMnets are  deleted and then added (this take about 7 minutes on my computer)
5. close gns3
6. start gns3 and do not load a project, wait until the GNS3 VM turns green
6. manually open your project 
7. drag the Ubuntu VM and back into the topology, but do not connect anything to it
8. start the Ubuntu VM
9. if the Ubuntu VM starts properly, stop the Ubuntu VM
10. connect back your interfaces
11. start the Ubuntu VM

**Comment by josephmhiggins** [comment]
Oh...and never go back into VMware and change any VMware VMnet settings for the VMware VM after you place it in the gns3 topology.

GNS3 takes over complete control of all VMware VMnet settings for the VMware VM.
You should not touch any network settings in VMware which are associated with that VMware VM.

**Comment by grossmj** [comment]
I found a workaround, please open the app from a terminal like this:

`SYSTEM_VERSION_COMPAT=0 open -a /Applications/GNS3.app`

**Comment by grossmj** [comment]
Fixed, it should work in our next release

**Comment by jacuinde** [comment]
thanks

**Comment by jacuinde** [comment]
confirmed working

**Comment by KubaOrluk** [comment]
VMware Fusion Player 13
OSX Ventura 11.6.7
GNS3 2.2.36

The issue is still there. The same "No VMnet interface available" error when trying to start Ubuntu Server 22.10. Workaround didn't work.
