### ISSUE TITLE
3.0 : Create QEmu Template : error : could not be found in the controller database

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3390]
Hi

On LiveRaizo v13 (Debian 11), and GNS3.0, i try to add a QEmu VM  

I remove my old GNS3's config with `rm`

I create a empty config of GNS3 3.0 `gns3server`, stopped by CTRL+C

I run `gns3`

In preference, i add a QEmu VM. I use default values except for disk : `/opt/raizo/user/OS/QEMU/VM-Raizo.raw`
I don't copy it in the default folder.

When i close the global preference menu, GNS3 displays this message : `2022-10-05 13:12:48 ERROR http_client:761 Image '/opt/raizo/user/OS/QEMU/VM-Raizo.raw' could not be found in the controller database`

**Comment by cristian-ciobanu** [comment]
I also confirm this issue is present, the workaround is to open the Image manager by going to File --> Image management then click Upload button to upload the image on the controller database.
Then you should be able to manually create a template.
I'm not sure if this is a bug or the template wizard does not list the proper steps to manually create a template.

**Comment by grossmj** [comment]
Have you put the path manually or have you used the browse button?

![Screenshot from 2022-12-27 10-00-22](https://user-images.githubusercontent.com/4752614/209599323-0ea54d3c-9d68-43bb-933b-0fa7a38b8703.png)

The image should have been uploaded after using the browse button.

**Comment by Raizo62** [comment]
I guess I had to use a copy paste
