### ISSUE TITLE
2.2.34 Boot Python Error

### ISSUE THREAD

**Issue by TomCos** [GNS3/gns3-gui#3400]
Hey everyone, looking for some advice.  Receiving the following error booting 2.2.34 install, upgraded from 2.2.19.

Python 3.10.8 is installed and the VM launches just fine.  3.10 is in the %path% variable as well.

```
C:\Program Files\GNS3>gns3.exe
Fail update installation: Module use of python36.dll conflicts with this version of Python.
Traceback (most recent call last):
File "C:\Python37-x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
File "C:\Python37-x64\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
File "gns3-gui\gns3\main.py", line 40, in <module>
File "gns3-gui\gns3\utils\get_resource.py", line 21, in <module>
File "C:\Python37-x64\lib\site-packages\pkg_resources\__init__.py", line 32, in <module>
File "C:\Python37-x64\lib\plistlib.py", line 65, in <module>
File "C:\Python37-x64\lib\xml\parsers\expat.py", line 4, in <module>
ImportError: Module use of python36.dll conflicts with this version of Python.
```

Windows 10 Pro 21H2

**Comment by grossmj** [comment]
> 3.10 is in the %path% variable as well.

What happens if you remove 3.10 from the %path% variable?

**Comment by OnkelbenzBB** [comment]
I got the same error after upgrade to "GNS3-2.2.34-all-in-one-dach.exe". I don't remember the previous version, but it was something from 2018.
My System is Windows 11Pro Version 22H2 and there wasn't any Python installation on system and no entry in %path% for it

**Comment by josephmhiggins** [comment]
As I explained in the original post,

python is a "powershell" command. this solves one mystery:
PSVersion is 5.1.19041.1682
This should solve one mystery
PS> get-command -all python* | ft -AutoSize

But something is going on with 
$HOME\Appdata\Local\Microsoft\WindowsApps

The posts at stackoverflow regarding
\Appdata\Local\Microsoft\WindowsApps
look to have some relevance.

But I have windows10 so that WindowsApps directory could be somewhere else and
it is a little bit confusing to me. Someone (with Windows 11) needs to research what that directory is all about.
I will check my Windows10 books briefly.

**Comment by josephmhiggins** [comment]
There is nothing in my books about that directory.
The original post on gns3 community was over here:
https://gns3.com/community/featured/2-2-34-python-error

The problem does not affect me on Windows 10 (and i have visual studio, visual studio code, both with the python extensions and python 2.7 and python 3.8 installed and the I have no python variables or python in my path and........everything works (except for GameBar which is a Microsoft Store App) here.

**Comment by eantowne** [comment]
"python is a "powershell" command."

@josephmhiggins Please explain this statement to me, as I have completely lost the train on this one.

"GNS3-2.2.34-all-in-one-dach.exe"

@OnkelbenzBB  Where did you get that installer from? I do not think "dach" has ever been in the filename for an official install package of GNS3.

@TomCos: Your experienced issue is most likely due to a conflict between the version of Python that you installed on the syste, and the version that is packaged to be installed and used locally by GNS3. As @grossmj asked, what happens when your remove Python 3.10 from the PATH environment variable?

**Comment by josephmhiggins** [comment]
@Ean,
"python" is a powershell command is explained in the original post.
In the post I asked Cos to escalate his problems because I found the whole problem very confusing - at the beginning.

The stackoverflow folks are saying that windows looks at \WindowsApps before checking the path variable  - and their posts are all about python. Someone is going to need to spend some time looking at that directory and seeing what it does.

**Comment by OnkelbenzBB** [comment]
I got this issue solved, you can hardly call it a bug, but its possible to check it while installation.
remainings from the previous installation, like python36.dll (but not alone) causes this problem. But if I just remove all old files, next issue appears, like "Fail update installation: bad magic number in 'PyQt5': b'3\r\r\n'"... So the solution is to remove all remainings from old installation and just reinstall GNS3

p.s. GNS3-2.2.34-all-in-one-dach.exe is the first free download for windows on https://gns3.com/

**Comment by josephmhiggins** [comment]
Yeah, that was my suggestion - to completely uninstall gns3 - with the strong caveat to backup the %appdata%\gns3
directory because my memory says that all that data gets wiped out - secretly - and then your template definitions which wipes out all your projects
