### ISSUE TITLE
GNS3 Version 2.2.35.1 supports Windows 11 VM

### ISSUE THREAD

**Issue by fatbell** [GNS3/gns3-gui#3414]
I'm trying out Windows 11 VM in GNS3 version 2.2.35.1 with a simple topology - Cloud, Windows 10 and Windows 11 VMs.  Windows 10 VM started but had timeout error for POST call for Windows 11 VM.  Is the VM supported in GNS3 v2.2.35.1?
![Windows 11 VM - Post Call Error](https://user-images.githubusercontent.com/17806351/207891088-75d00762-9f2a-46ba-bcc2-d2860565a6e2.PNG)
![Windows 10 and 11 VMs in GNS3 2 2 35 1](https://user-images.githubusercontent.com/17806351/207891090-17926ed5-5555-43a1-b0d6-79ca1bdbf850.PNG)
[Windows 11 VM - POST Call Error.txt](https://github.com/GNS3/gns3-gui/files/10238015/Windows.11.VM.-.POST.Call.Error.txt)
  

Host - Windows 10 Pro
VMware Workstation 17 Pro
GNS3 Version 2.2.35.1

**Comment by eantowne** [comment]
1. You should not be able to have 2 different nodes connected directly to a "Cloud" node. While you may be connecting each one to different interfaces of the cloud, I would not trust that.
2. Curious if this is a GNS3 issue, or VMware interaction issue, as the VM is running on VMware and being integrated into the GNS3 project.
3. If you disconnect the Windows 11 VM from the "cloud", will it boot?
4. If you shutdown and remove the Windows 10 VM, will the Windows 11 VM boot?

Also, are these the Microsoft created trial VM's? Or did you create these VM in VMware Workstation?

**Comment by josephmhiggins** [comment]
no...this is a whole big thing Ean.

the way gns3 is troubleshot and implemented vis a vis the gns3 cloud is all based on David Bombal.

I just spent 10 hours with tisou on this:
https://gns3.com/community/featured/vmware-vm-network-doesnt-work-in-gns3
the way that david does it is the right way.

to the best of my knowledge eth0, eth1, or eth2 mean nothing on the gns3 cloud.
someone would have to look in the gns3 code.

i can delete all vmnets in vmware and add a
vmnet1 host-only first or i could a vmnet8 nat interface 1st or i could add a bridged interface 1st.

I need no vms in my topology - i only need wireshark - I do not even need wireshark. I only need powershell and the ip address of the gns3 vm so i can logon to it.

Umm, again back to you Ean, we wait until 3.0, but then this is an architecture decision by the gns3 developers.
**_Do they want to have a laissez-faire approach to this or not._**

When I load that .gns3 file, I will know if everything is configured properly in vmware or not.

![topology](https://user-images.githubusercontent.com/85327995/209243803-be24a358-9801-400c-b788-9eb9480f33e6.PNG)

gns3 users do not install gns3 and run over to see what david bombal says to do.
i do not make a move on anything without seeing if david bombal said to do something a certain way.

**Comment by josephmhiggins** [comment]
@fatbell,

You abridge your picture to your error.
Please do not copy and paste pictures of text.
Copy and paste text of text.

Timeout error for POST is abridged so I do not know what it says.

For gns3 version < 3.0, there is a bit of a problem that only a linux expert or the gns3 developers would know.
But the TIMEOUT limit for the GNS3 VM is definitely, unquestionably not valid - but that is a gns3 version < 3.0 situation.
I am a windows users, but the proper design for gns3 < 3.0 would be something like this in powershell (this is how I do it)

        # The GNS3 VM has been started. Get the ip address of the GNS3 VM
        $Gns3VMIP = & $GetVmrunResultSB -cmd $vmrunip

        $Vmnet1Params = @{
            InterfaceAlias = 'VMware Network Adapter VMnet1'
            AddressFamily  = 'IPv4'
        }
        $Vmnet1 = Get-NetIPAddress @Vmnet1Params
        $Vmnet1Address = $Vmnet1.IPAddress
        $msg = "Attempting TCP Connect from $Vmnet1Address to " +
               "remote $Gns3VMIP and remote port 80."
        # FROM VMNET1 INTERFACE
        Write-Verbose -Message $msg -Verbose

        # Put the TcpClient in a while loop with a maxtime of 300s
        $tcpresultparams = @{
            TypeName    = 'System.Net.Sockets.TcpClient'
            Argument    = $Gns3VMIP, 80
        }

        $StartGNS3TimeLimit = 300
        $TimeOut300 = New-TimeSpan -Seconds $StartGNS3TimeLimit
        $StopWatch = [Diagnostics.Stopwatch]::StartNew()
        While ($StopWatch.Elapsed -lt $TimeOut300) {
            try {
                $tcpresult = New-Object @tcpresultparams
                # If New-Object threw no error, then it succeeded.
                break
            } catch {
                # New-Object can throw a terminating error, catch it.
                $attempts += 1
            }
        }

        # Unknown at this point if TcpClient Connected successfully
        # because TcpClient could have timed out after $Timeout, test it.
        if ((-not($tcpresult)) -or ($tcpresult.Connect -eq $false)) {
            $msg = "TCP timer expired after $StartGNS3TimeLimit seconds " +
                   "and $attempts attempts."
            Write-Verbose -Message $msg -Verbose
            throw $msg
        } else {
            $FinishTime = Get-Date
            $ElapsedTime = $FinishTime - $StartTime
            $Duration = $ElapsedTime.totalseconds.tostring('n1')
            $msg = "Total time to establish TCP connection " +
                   "to the GNS3 VM was $Duration seconds."
            Write-Verbose -Message $msg -Verbose
        }

I do not know why the GNS3 VM times out.
You may have more than one problem here..............again, per Ean,
we just might have to wait for gns3 version 3.0

**Comment by josephmhiggins** [comment]
@fatbell,
you specifically have to deal with what tisou got after 10 hours:
at Dec 22 2022 at 10:07pm in his post

as far as the Timeout is concerned, that is really a gns3 vm/gns3 developer/linux problem

in windows, if you left click on the gns3 vm in task manager and kill it, the gns3 vm will not like that and may take longer to reboot and i do *not* like the gns3 timeout limit in gns3 < 3.0. But, i have no say in the matter.

you should ensure that the gns3 vm is named GNS3 VM and not named shimshamvm
you should ensure that the gns3 vm vmdisks are installed in the default directory %homepath%\Documents\Virtual Machines\GNS3 VM
you should ensure that only the gns3 vm starts when gns3 starts and no other vm in vmware starts

...and of course there could be a problem with gns3 version 2.2.35.1, but you should have confirmed all of the above.

**Comment by eantowne** [comment]
@grossmj I am going to apologize a head of time, and feel free to block me from these repositories and the community on gns3.com, if you feel it is deserved. I cannot hold back any longer.

Ok, now I am invested. Before I get into this, @josephmhiggins, I appreciate the effort you put into the community on GNS3. You have been a consistent force to try and assist the user-base. If you are thin skinned and prone to self-confidence issues, you might not want to read the remainder of this. I am not trying to hurt your feelings, but there are some things that I feel the need to express.

My response was designed to try and get more information from the person submitting the issue in order to try and determine an actual cause. Issue submission is for feature requests and bug reporting, not really for troubleshooting problems, except to determine the cause of a bug. Based on the VERY limited data the submitter provided, I considered the issue as being worthy of investigating to try and help Jeremy as he has his hands more than full. You however decided to jump to a conclusion based on recent experiences in a community post that may or may not have any relevance to the issue at hand. You then proceeded to provide the verbal equivalent of diarrhea. This does not provide any meaningful contribution to this issue. More than once, you state that you don't know, nor have the expertise.

I would now like to address some of your statements, starting with a statement from the referenced community post. 

"(okay, this is the last shot because it is the end of my day and I have been coding for 12hours)
(this is a dangerous time for me because I make mistakes when I am tired)" - This is good advice, and should be heeded.

"the way gns3 is troubleshot and implemented vis a vis the gns3 cloud is all based on David Bombal." - No, while David is a great content creator and a truly intelligent individual, he is not the source of truth regarding the function of GNS3. I would argue that Jeremy holds that enviable position.

"the way that David does it is the right way." - The way that David does it is **A** right way. Please refer to my statement above.

"to the best of my knowledge eth0, eth1, or eth2 mean nothing on the gns3 cloud.
someone would have to look in the gns3 code." - If this statement had any resemblance to reality, then devices in a project could get 192.168.122.0/24 addresses (specifically provided by the DHCP server on the virbr0 interface, which in case you are unaware is the interface for the NAT node in GNS3 on Linux or the GNS3 VM) when bound to eth0 or any of the other ethx interfaces. I am not saying that is impossible, but I have **NEVER** seen that happen, and I would be surprised if you could honestly prove to me that it has.

"we wait until 3.0, but then this is an architecture decision by the gns3 developers.
Do they want to have a laissez-faire approach to this or not." - Honestly, no idea what you mean by this.

"When I load that .gns3 file, I will know if everything is configured properly in vmware or not." - No relevance to the issue submitted.

"gns3 users do not install gns3 and run over to see what david bombal says to do.
i do not make a move on anything without seeing if david bombal said to do something a certain way." - Ok, I get it, you have a man crush on David, fair enough. There are worse people to crush on. Ignoring that, your statement poses the idea that if you do something other than what David has done in a video, it is wrong? Or better yet, to use a phrase you like to use, "illegal". I will 100% stand here and say, I understand that I might get struck by lightning, that David Bombal does not know everything. There, I said it. Do I know more than David, maybe, maybe not. Most likely that depends on the subject. I am confident that if you were able to ask David if he was the one and only source of truth reference GNS3, he would say no. I am also confident in something else, there is nothing "illegal" about the things you say that  are.

"and......Tisou looks to have made his "deb-vm" the 'gns3 vm' because he named the "gns3 vm" "gns3" - that crushed me." - What is your point here? Do you think that there is some immutable law of physics that mandates the specific name of the virtual machine? I could create a VM called "Illegal_GNS3_VM" and make it work as a GNS3 VM.

"Timeout error for POST is abridged so I do not know what it says." - If you look at the top-right corner of that **EXACT** same image, you will see the full error text. I will give you a hint seeing as how you have been "coding" for 12 hours, look at the red box.

"For gns3 version < 3.0, there is a bit of a problem that only a linux expert or the gns3 developers would know." - Yet, you feel the need to comment on it?

"But the TIMEOUT limit for the GNS3 VM is definitely, unquestionably not valid - but that is a gns3 version < 3.0 situation." - What in the name of all of the PowerShell snippets does this mean and what bearing does it have on troubleshooting the actual problem?

"I am a windows users, but the proper design for gns3 < 3.0 would be something like this in powershell (this is how I do it)" - Trying not to bang my head against the wall, but you are really making it hard for me. This one requires me to use a bulleted list to properly respond.

- You are now convinced that you can better program the functionality of GNS3?
- Your PowerShell script is simply a wrapper that tests a TCP connection, does some logging and launches the GNS3 client. How does that fix anything?
- For the record, the P and the S in PowerShell are capitilized. Evidence: EVERY single MS website that talks about PowerShell.
- Reference the first bullet, ok, if I accept your premise, where are your commits? How are you helping Jeremy? Please use your brilliance to help GNS3 be a better solution.

"I do not know why the GNS3 VM times out." - After all of that, you mean to tell me that you do not know what the problem is? Are you getting paid by the word or something? All of that and you have NOTHING to contribute to the issue?

"You may have more than one problem here..............again, per Ean," - Now you agree with me? This seems counter to your previous statement of, "no...this is a whole big thing Ean.".

"we just might have to wait for gns3 version 3.0" - So, you do not know what the problem is, nor the solution. You then propose that GNS3 3.0 will provide a solution?

"as far as the Timeout is concerned, that is really a gns3 vm/gns3 developer/linux problem" - Then why are you even in the conversation? You have stated numerous times that you are none of those, but you felt the need to provide commentary all over this issue? The "timeout" issue is the primary symptom of the problem!

"in windows, if you left click on the gns3 vm in task manager and kill it, the gns3 vm will not like that and may take longer to reboot and i do not like the gns3 timeout limit in gns3 < 3.0. But, i have no say in the matter." - Bullets, yet again.

- The GNS3 VM is software, bits, ones and zeros. It does not have feelings. Anthropomorphism of code is a bad habit.
- The GNS3 VM is not affected by the client exiting, the gns3server process might have some issues, but that would just be a connection going stale.
- Why would it cause the VM to take longer to reboot? That is like saying that dropping a spoon in the kitchen will cause the milk in the fridge to curdle.
- Please provide me some form of evidence that the "timeout" problem will be resolved in 3.0. It might, I don't know, then again, I do not think I have ever experienced the "timeout" problem like you apparently have. Seems strange, since I do not do things the "David Bombal" way.

"you should ensure that the gns3 vm is named GNS3 VM and not named shimshamvm" - I am sorry, once again, but the name of the VM means nothing because you can specify which VM the client connects to. Even better, Just configure as a "remote server" and only deal with the IP, and no one will ever care about the name of the VM.

"you should ensure that the gns3 vm vmdisks are installed in the default directory %homepath%\Documents\Virtual Machines\GNS3 VM" - Nope, sorry, but I can store .vmdk files anywhere, and as long as I have the correct permissions to access, and I configure the VM settings in the hypervisor, it will work fine.

"you should ensure that only the gns3 vm starts when gns3 starts and no other vm in vmware starts" - Also, not a valid statement. I could start 37 VM's at the same time as the "shimshamvm" and it will not stop me from being able to connect the client to the "shimshamvm".

"...and of course there could be a problem with gns3 version 2.2.35.1, but you should have confirmed all of the above." - Yet again, you are basically saying that you do not know what the problem is, and not trying to assist in determining the parameters of the issue at end to allow Jeremy to determine if this is a bug or not.

There is a lot more that I would like to say. However, I am fairly certain that I have said enough. I tried to use this an opportunity highlight a behavior that you express quite often. I am concerned how this behavior affects those that are seeking help with the use of GNS3.

**Comment by trakatelis** [comment]
Hi fatbell,

Could you possibly downgrade to GNS 2.2.34 and post the results?
I noticed a problem with specifically the Windows installation of GNS 2.2.3.51 connecting to the cloud.

> Host - Windows 10 Pro VMware Workstation 17 Pro GNS3 Version 2.2.35.1

**Comment by josephmhiggins** [comment]
Sorry Ean, I was a little upset.
@fatbell,
i recommend 
1. stop gns3
2. stop vmware
3. renaming your gns3 directory where your gns3 vm to gns3-vm-bad
4. remove whatever vm you are using for gns3 from vmware
5. start vmware
6. download and install a new gns3 vm in vmware
7. only install it with the name GNS3 VM and in the default location %homepath%\Documents\Virtual Machine
8. do not start gns3; gns3 < 3.0 will try to start the gns3 vm; gns3 is not required to test the functionality of the gns3 vm; the gns3 vm should always be started on windows first - before gns3 is started; i started the gns3 and the gns3 vm about 100 times yesterday alone
9. start the gns3 vm
10. get the ip address from the gns3 vm information screen; ping that ip address

People are reporting problem with gns3 2.2.35.1 on windows

You do not need gns at this time. Do not start gns3. Below gns3 < 3.0, having gns3 start the gns3 vm is an incorrect design.
The gns3 vm must be started first and must be tested to be in a working condition before starting gns3.

**Comment by fatbell** [comment]
> 

Thank you all for your contribution. @josephmhiggins I have done as recommended this time I'm using version 2.2.34 VM.  I can ping GNS3 VM IP address.  Windows 11 VM runs in VMware Workstation 17 Pro but not in GNS3 GUI - Edit-->Preferences-->VMware VMs.  I'm getting the same Post Call Error.
![GNS3 VM version 2 2 34](https://user-images.githubusercontent.com/17806351/209351646-8b9ce637-e2bc-417e-b3a2-80ce56787420.PNG)
![Ping Result - GNS3 VM IP Address](https://user-images.githubusercontent.com/17806351/209351695-d62ea079-8ec0-4727-8ea4-0ff2734859d8.PNG)
![Windows 11 VM in VMware Workstation 17 Pro](https://user-images.githubusercontent.com/17806351/209351758-f46bed65-ca05-409f-b831-fca165ae90f3.PNG)
![Windows 11 VM - Post Call Error in Version 2 2 34](https://user-images.githubusercontent.com/17806351/209351786-
eab75edc-a3d5-45c2-822c-f586800c35e7.PNG)

**Comment by fatbell** [comment]
Sorry re-posting the last screenshot
![Windows 11 VM - Post Call Error in Version 2 2 34](https://user-images.githubusercontent.com/17806351/209352428-98c59c0a-1a39-4644-8492-1f9b8ecfb070.PNG)

**Comment by josephmhiggins** [comment]
Oh, so let's break this down.

You installed gns3 vm 2.2.34.
The gns3 vm 2.2.34 is brand new.
By default, the gns3 vm 2.2.34 will not have project '1379*' on it.
The project '1379*' exists on your gns3 vm 2.2.35.1

The gns3 developers support upgrading the gns3 vm from 2.2.34 to 2.2.35.1.
But, the gns3 developers do not support downgrading the gns3 vm from 2.2.35.1 to 2.2.34

One of the major problems with gns3 < 3.0 on windows when you run gns3 on the local host, as opposed to running it on a remote server, is that your .gns3 file exists on your Windows host.
Your .gns3 file on your Windows host has become 'dereferenced'.
Your .gns3 file is broken.

If you are a new gns3 user, the fastest and easiest way is just to
1. click away the errors
2. delete those nodes in the gns3 topology and the gns3 topology alone - do not delete them if they exist in vmware
3. put the nodes back in the gns3 topology

However, if you are a long time gns3 user, then you may have to do this with every project you have.

It *may* be possible to recover all your old projects.
But that has never been done before - to the best of my knowledge.
That could take a lot of time to recover all your old projects.
Each project will post that Timeout error.
That will be frustrating to deal with - imho.

I have been using gns3 for too long and you escalated to the gns3 developers, so I would just say forget about all your old projects and rebuild them all one at a time.

The primary focal recovery point for projects on Windows and gns3 < 3.0 is you must take a picture of every topology using the little camera button in the gns3 gui and put it in the directory of the project. You want to also have any text configurations you have done on any device directory. You also want to have also have any ssh/telnet logs stored for any sessions in that directory.

**Comment by josephmhiggins** [comment]
@fatbell,
This post can be closed.
You can deescalate to the gns3 community board if you want to try and recover all your old projects, but I have no confidence that I will help you at this time of the year.

The root cause of this problem is:
on windows, the gns3 developers incorrectly designed gns3 to have gns3 start the gns3 vm in vmware without verifying the gns3 vm was 'up and running'/'configured properly'.

The term 'configured properly' is really a gns3 architect decision and it is simply do they want new gns3 users learn how to 
configure vmware on their own. I have thought about this for the last 3 years. If gns3 wants to let gns3 users learn how to configure vmware on their own, then I accept that.

I do not accept the gns3 developers design to not start the gns3 vm first, e.g. before gns3.

Please close this post.

**Comment by fatbell** [comment]
@josephmhiggins,

Thank you for your help.
