### ISSUE TITLE
Allow changing preferences when "Please wait" popup appears

### ISSUE THREAD

**Issue by itsamemarkus** [GNS3/gns3-gui#3492]
**Describe the bug**
When the GNS3 VM isn't available or you entered the wrong IP there is a popup

`Please wait, waitig for http://<GNS3-IP>`

![image](https://github.com/GNS3/gns3-gui/assets/34944988/c7159c4e-0f69-4871-a257-413589e51d5a)

This pops up a few times. During this time you can't change the preference to fix the error.

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 11 - 22H2 Build 22621.1928
 - GNS3 version: 2.2.40.1
 - GNS3 VM on Hyper-V

**To Reproduce**
1. Change IP in preferences to one where no GNS3 server runs
2. Wait for error (I think the error pops up faster when target port is also open on the IP you entered)
3. Try to change settings
4. Error popup prevents you from changing settings

**Screenshots or videos**

(there is sound where you can hear when I tried to click and it wouldn't let me)

https://github.com/GNS3/gns3-gui/assets/34944988/8dfaf62e-6eea-4e50-bc58-c94822704498

**Comment by josephmhiggins** [comment]
Yeah, it is a little frustrating in gns3 version < 3.0 because you are bound to be in a position of constantly being drawn back to the Please wait Active Window.
The simple solution is to "plan ahead" and turn off the gns3 vm before closing gns3 - but who does that?
Or you can open up powershell and type
stop-process -name gns3
and then manually edit the gns3_server.ini for any changes I want to make, or start gns3 the next time with a new profile
- but who does that?

I completed my script to start gns3 yesterday and the final piece was to wait until the main window opens and then immediately trigger to minimize the window and wait until the gns3_server.log  writes to the log file that the "gns3 vm is online". The rationale for doing it this way is because it appears some gns3 users run into strange bugs by changing the preferences, from the gui, before the gns3 vm is online. I think it is very bad to do anything in the gns3 gui until the gns3 vm icon is green. I leave my gns3 vm running all the time but I have chosen to restart the gns_server.exe each time I start gns3. It takes 20 seconds for the gns3 vm to come online on my machine, so patience is required.
We just have to wait for gns3 version 3.0 to prevent all of this.
