### ISSUE TITLE
Request for Key-Shortcut and, Link-Connection Visibility

### ISSUE THREAD

**Issue by MaurizioCal** [GNS3/gns3-gui#3607]
Dear GNS3 Team
Dear Jeremy Grossmann 

I would like to ask you kindly here. Please would it be possible to store a key combination for “Fit in View” I need this option a lot, and it would certainly be faster with this Option.
![fit-in-view](https://github.com/user-attachments/assets/c473b9ab-fa43-4f5b-820e-b5db38cd340f)

And please see also picture "Down" here the Router R4,R5,R6,R7 this Ports are Down, why this will appair in color Green. its here possible to assign the Green color only if the links together are running and Connected? If you see Red points on a running LAB you see quick where are running any issue, so the overview, what are connected and not, it's quick visible.
![Down](https://github.com/user-attachments/assets/33406844-8985-48b0-9d87-5ecc6e02fb99)

Also possible? if you have a setup like this here to visualize the packet flow. For example if you play with the option Metric/Cost/FD etc. so that you receive a Visual overview.

Thanks for this application that i use so often, GNS3!
Maurizio

**Comment by grossmj** [comment]
> And please see also picture "Down" here the Router R4,R5,R6,R7 this Ports are Down, why this will appair in color Green. its here possible to assign the Green color only if the links together are running and Connected? If you see Red points on a running LAB you see quick where are running any issue, so the overview, what are connected and not, it's quick visible.

At the moment, the color is only is only to show if a node/link is started / suspended / stopped in GNS3 since we cannot know (not easily at least) what are the real link status inside the operating system running in different nodes. To us, whatever is running in a node is like a black box.

> Also possible? if you have a setup like this here to visualize the packet flow. For example if you play with the option Metric/Cost/FD etc. so that you receive a Visual overview.

This is a similar problem as above, we would need to know what is flowing on a link or get some stats. This will be more feasible once we have a new network back-end.
