### ISSUE TITLE
If you turn off local server you got Local server is not running when interacting with GNS3VM

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#442]
Step to reproduce:
* turn off local server
* go to the GNSVM
* switch from VMWare to VirtualBox
* you got this error
![capture d ecran 2015-06-18 a 15 27 55](https://cloud.githubusercontent.com/assets/345437/8232277/a27c6c40-15ce-11e5-947d-60f785633092.png)

**Comment by noplay** [comment]
So the issue is if you have a local server but not started by GNS3 you can't use the GNS3 VM.

**Comment by noplay** [comment]
I think we can use the localServer().connected()  method instead isLocalServerRunning() and test the connection to local server at startup instead of instead of when we drop the first node.

**Comment by grossmj** [comment]
Sounds good. Actually the local server is only needed when configuring the GNS3 VM the first time since it uses the search capabilities in the server to find the VMs.

Not totally satisfied with this part either... I was trying to avoid duplicate too much code, should we have a meta package for both the GUI and server where we can move this kind of things?
