### ISSUE TITLE
Allow bridged interface for the GNS3 VM? 

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#534]
https://github.com/GNS3/gns3-gui/issues/530#issuecomment-120593835

**Comment by ehlers** [comment]
The reason for this question is, that I want the GNS3 server (local and the VM) to be able to connect to other servers. With the host-only interface that's not possible. I admit, that this is maybe an unusual case, but it's very easy to allow it.

**Comment by ehlers** [comment]
I thought about it. Allowing bridged interfaces defeats the intention to have a tightly controlled environment, which is easy to support and which is portable.

People like me, who use the VM for extended purposes, can use the VM as a "normal" remote server with the customization they like. The projects, created by such an unusual configuration, are not portable anyway.

**Comment by grossmj** [comment]
We can definitely have this as an advanced option, really simple to do. The advantage is that your projects will be more portable because the IP of the GNS3 VM is not recorded in the .gns3, it is dynamically found when your open a project.

**Comment by ehlers** [comment]
With the portability issues on bridged interfaces I meant the following:
For a "normal" lab with only the GNS3 VM and the local server involved, you don't need the bridged interface, the host-only interface is sufficient. An advanced project, where the GNS3 VM has connections to other GNS3 servers can't be portable, because another non-standard VM is involved.

But I don't want to argue too much against my own suggestion. For VirtualBox I have created a (really simple) implementation, see https://github.com/GNS3/gns3-gui/issues/530#issuecomment-120593835. But I can't test VMware (I have only an "ancient" VMware Fusion 5 on my Mac). So i don't know if ```self._vm.execute_vmrun("getGuestIPAddress", ...``` is working on a bridged adapter.

**Comment by grossmj** [comment]
```
With the portability issues on bridged interfaces I meant the following:
For a "normal" lab with only the GNS3 VM and the local server involved, you don't need the bridged interface, the host-only interface is sufficient. An advanced project, where the GNS3 VM has connections to other GNS3 servers can't be portable, because another non-standard VM is involved.
```
I agree. Just I am sure someone will come up with a request to access the GNS3 VM remotely ;)

```
But I don't want to argue too much against my own suggestion. For VirtualBox I have created a (really simple) implementation, see #530 (comment). But I can't test VMware (I have only an "ancient" VMware Fusion 5 on my Mac). So i don't know if self._vm.execute_vmrun("getGuestIPAddress", ... is working on a bridged adapter.
```

I am confident this would work on VMware. For info getGuestIPAddress is only available in recent versions of the VIX API and it works with bridged interfaces too.

**Comment by noplay** [comment]
I think a robust way is to allow users to add a third interface to the VM:
https://github.com/GNS3/gns3-vm/issues/30

**Comment by grossmj** [comment]
I was thinking the same. Add support for a third user added interface should do it.
