### ISSUE TITLE
Show a warning when the GUI is run with root rights

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#608]
https://community.gns3.com/ideas/1856#comment-12968

**Comment by ehlers** [comment]
Good idea (oh it's mine :-), but then the help texts for cloud interfaces should be also changed. Otherwise the user is irritated, when he is warned against running GNS3 as root and on the other side root access is required for the cloud interfaces.

Ethernet NIO:
Generic Ethernet NIO (Administrator or root access required)
Linux Ethernet NIO (Linux only, root access required)

TAP:
TAP interface (require root access)

I suggest changing the help texts to an URL, where an in-depth description of the cloud configuration can be found. Something like the "Cloud Nodes" section of the Book of GNS3. Of course, we can't simply use that, it's copyrighted.

**Comment by noplay** [comment]
Agree about changing text.  I just read again the chapter in the book of GNS3 and for linux and OSX you have no good reasons.

**Comment by noplay** [comment]
We can show only a warning message instead of an error. Saying running GNS3 as root or admin prevent usage of VirtualBox and VMware because it's the most common problem with root.

**Comment by ehlers** [comment]
I totally agree, that the user shouldn't run GNS3 (or any other application) as root. I myself run GNS3 on both Linux and Mac OS X without root privileges.

The only thing I like to highlight is, that I haven't found a good explanation besides the book of GNS3 how to do that. As I don't think, that access to that book should be mandatory, the user should be directed to some documentation about a root-less setup.

**Comment by noplay** [comment]
Yes and promoting way to avoid cloud interface. 

For example you can get internet by using the internet VM in the GNS3 VM. It's a bit hacky under the hood but work.

Also if you add a bridge interface to the GNS3 VM the cloud adapter could be used out of the box.

**Comment by ehlers** [comment]
Making the cloud a real object should make things easier.

**Comment by grossmj** [comment]
I will wait we have a better documentation about it.

**Comment by grossmj** [comment]
For comparison. Starting Wireshark in root:

![wireshark_root](https://cloud.githubusercontent.com/assets/4752614/13798395/8e435abc-eadb-11e5-9300-61f23ea34185.png)
