### ISSUE TITLE
Add the posibility to choose the console application at the node level

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#675]

**Comment by grossmj** [comment]
The command line should then be stored at the template level.

**Comment by grossmj** [comment]
Actually, wouldn't it make more sense to have this applied at the template level instead of node? Saving a custom command line in the topology is not a good idea I think.

**Comment by noplay** [comment]
To be honest I don't see the real world use case :( Why you want changing  the console for a template or a specific node.

I agree that storing the console in the topology doesn't seem a good idea. Perhaps we can rollback this part of the change.

For VIRT or RDP the issue is not solved since the implementation need to be  like VNC with a console type because we need also to start the emulators with correct arguments.

**Comment by noplay** [comment]
I will make a PR with a different approch allow to open a custom console on a node without save.

**Comment by grossmj** [comment]
Doing it at the template level, you don't have to change the node to a custom console everytime. It's already there when you drop it on the scene. Then the custom console can be saved in the preferences settings. Anyway, it is true I don't see a strong use case for now, it just give more flexibility. However, I insist saving a custom command line in the topology is like shooting ourselves in the foot ;)

**Comment by noplay** [comment]
Yeah that why I pushed PR #1022 to avoid saving.
