### ISSUE TITLE
Change server IP addresses/hosts in project files

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#742]
Originally discussed in https://github.com/GNS3/gns3-gui/issues/506

We should provide an user friendly way to change the IP/host for servers in project files for better portability. I am more thinking about a tool to edit server addresses in a project file or propose to change one if a server cannot be reached when loading a project.

**Comment by noplay** [comment]
An important point is that user need to understand it should be the same servers. Otherwise their data will be lost.

**Comment by grossmj** [comment]
More something we may do in 1.5 part of the portability re-factoring.

**Comment by noplay** [comment]
Could be solved by #957

**Comment by noplay** [comment]
Since we have the remote GNS3 VM we didn't get support message asking us how to do that. Because you can just change the remote GNS3 VM in preferences. Even better user switched from local to remote GNS3 VM. And now we have also user with full remote project.

I'm not sure it still usefull to have an interface to  do it. The only case where it's usefull it's when you where working with multiple remote server and changed the IP of one.

My concern about having an interface is people can think they can update the project file and it will work. And think it's move function. But it's not true you need also to move the data.

**Comment by grossmj** [comment]
Agreed.
