### ISSUE TITLE
ASA flash lost during import

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#816]
Reported by @jean-christophe-manciot:
After the ASA project has been imported from .net to .gns3, the folders qemu/vm-n are empty.
This behaviour is the same on Windows and Linux versions.

In GNS3/Linux 1.3.1, the flash files are now created but something is lost during the import process: ~19 kB vs ... ~19 MB. The ASAs do not start.

**Comment by grossmj** [comment]
What should we do with this one? ASA 8 is not recommended...

**Comment by noplay** [comment]
I have look on this. We will probably pass hours on this topic for at the end the user getting blocked during the boot process.

I opened a PR to gns3 converter to raise an error when trying to import ASA 8 appliance:
https://github.com/dlintott/gns3-converter/pull/30

**Comment by jean-christophe-manciot** [comment]
I tried to convert a 0.8.7 project with ASAs with latest GNS3 1.4 & converter: the qemu folders are created but are empty.
I suppose that all that is left to do is to convert the FLASH file (from raw?) to qcow2 with qemu-img and put it into the right folder. This shouldn't be a big deal.

**Comment by grossmj** [comment]
Have you tried to manually copy the FLASH file to this if it solves the issue?

I think there is a potential issue because the base image path hard coded in the FLASH file (Qemu disk). That means the Qemu VM will not work if you move your project to another host on which the base image is located somewhere else.

To check this path you can use qemu-img on the file. Example:
```
qemu-img info hda_disk.qcow2 
image: hda_disk.qcow2
file format: qcow2
virtual size: 2.0G (2147483648 bytes)
disk size: 196K
cluster_size: 65536
backing file: /home/grossmj/GNS3/images/QEMU/IOSvL2-15.2.4.0.55E.qcow2
Format specific information:
    compat: 1.1
    lazy refcounts: false
```

There is a way to change it. Example:

```
qemu-img rebase -b /home/grossmj/GNS3/images/QEMU/IOSv-15.5.3M.qcow2 hda_disk.qcow2 
```

**Comment by jean-christophe-manciot** [comment]
Well, there is no "backing file" with ASA's FLASH:
root@samsung-ubuntu:/home/actionmystique/Program-Files/Labs/GNS3/CCNP-Security/FIREWALL/Jean-Christophe_Manciot/0.8.x/Data Center ASA - ASDM - AAA - VMs/working/ASA_5520_1# qemu-img info FLASH 
image: FLASH
file format: qcow2
virtual size: 256M (268435456 bytes)
disk size: 19M
cluster_size: 65536
Format specific information:
    compat: 0.10
    refcount bits: 16

Anyway, why is no FLASH copied during the conversion?

**Comment by noplay** [comment]
No file is copied for qemu at this time. Daniel as not finish the support
of Qemu.

**Comment by jean-christophe-manciot** [comment]
Manually copying the FLASH images is tedious because we also have to map the node name with the UUID from the gns3 file & manually configure the node with the right HDD, but **it works because we get all the node running-configuration back**, and you're right, without the need for any conversion.
However, we also need to manually modify the paths of initrd and vmlinuz in the .gns3 when they change; the GUI does not offer an image from the default path "my binary images" when the former one does not exist anymore.

**Comment by grossmj** [comment]
> Well, there is no "backing file" with ASA's FLASH

You are right, forgot we use initrd/kernel to run the OS.
