### ISSUE TITLE
GUI function to delete project

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#822]
From @ehlers.

In the good old days of GNS3 v0.x it was easy to delete a project, just delete the subdirectory in GNS3/projects. But with v1.x files are also created on other (remote) GNS3 server. So it gets increasingly difficult to cleanly remove all the files belonging to a project.
 
So I propose a function in the GUI to cleanly remove a project, including the project files on remote servers.

**Comment by grossmj** [comment]
@noplay any input on this?

**Comment by grossmj** [comment]
This can probably wait for the re-factoring we intend to do in 1.5

**Comment by ehlers** [comment]
If you want, I have a python stand-alone program to delete a project. It supports https connections to remote server, but not ssh. because it's stand-alone, It includes some redundant functions. I supports both python 2.7 and 3.x, so some parts are not really elegant.

I'm fine with the 1.5 time frame.

**Comment by noplay** [comment]
We decide to drop ssh in order to simplify stuff :)

**Comment by 1001QAdotNET** [comment]
can I understand that for now we have to delete the project manually? I just realized that after so many tries I now have 6.7G of projects? Where can I read more about the way GNS3 hndles the project files and how the configs are saved for various appliances (in particular for vIOS and IOU) ?

**Comment by noplay** [comment]
Yes delete is something missing. The problem is we need to have a complet interface for managing projects from a unique location. Moving from the old system where people just manage their project from their local hard drive.

It was not a real problem with IOU since project are small but Qemu based create more troubles.

If you are using the GNS3 VM everythings is in _/opt/gns3/projects_ with a directory by project. Temporary project are automatically garbage collected.

But it's the project UUID and not the project name (since you can have multiple project with the same name).

Each project contain a directory by VM type. This directory often contain a sub directory by VM with the data.

For IOU it's the startup-config and the NVRAM
For IOSv it's a disk image linked to the original IOSv image.

We want to finish the work to have a clean project system in 1.5.

**Comment by 1001QAdotNET** [comment]
I think that storing the gns3 file (the project file) for a remote project locally it is wrong because it confuses the user. All the files for a project should reside on the same media.

Is the linked base image saving space for qemu projects?

**Comment by noplay** [comment]
The linked yes save space.

The problem is you have part of the project running local and part remote, it's what is generate complexity.

**Comment by 1001QAdotNET** [comment]
True, I did not realize that that could be the case
In the case of a linked image, let's say that is vIOS, how do you save the switch/router configs for devices that share the same linked image ?

**Comment by noplay** [comment]
In the VM directory you have an overlay disk:
https://en.wikipedia.org/wiki/Qcow

**Comment by noplay** [comment]
Where we should locate this? In the File menu an entry delete project with a confirmation?

**Comment by noplay** [comment]
Done
