### ISSUE TITLE
The "please wait" box problem.

### ISSUE THREAD

**Issue by superwolfboy** [GNS3/gns3-gui#925]
1,Once the "please wait" box was showing the percentage, it can not be force close by click "X", when click, the box will appear again, until finish or out of time. In the privious version it can be close forcly and the console will show a warning message.
2,Sometime the "please wait" box will blink for a while until the process finished. For example when I calculate the idle-pc, the box will appear and disappear again and again, until idle-pc got.

**Comment by noplay** [comment]
I will say it's work as designed but could be enhanced. 

1) we need to remember that you have close the windows for current operation and all the operation in queue until the queue is empty
2) idle pc consume 100% of CPU I think it could trigger the blink.


This dialog could be improve, but it's sensitive. Due to the multi thread it's easy to create situation where the progress dialog never disapear.

**Comment by superwolfboy** [comment]
maybe the "please wait" dialog box should show a progress bar with or without percentage,
yes without percentage is OK also, blink is not so good, looks like somthing wrong :)

**Comment by grossmj** [comment]
Blinking is not normal. I see it more often, always on Windows.
