### ISSUE TITLE
[Linux/1.4.0] Allow expansion of the width & height of the Preferences Window to cover up the whole display

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#948]
It used to be possible in earlier releases to expand it up to the max size of the display, now its expansion is limited to the following:
![preferences window size limitation](https://cloud.githubusercontent.com/assets/13176858/12490273/f7128004-c074-11e5-8bbb-dc8f45cddaa0.jpg)

**Comment by noplay** [comment]
Most of code is here:
https://github.com/GNS3/gns3-gui/blob/master/gns3/dialogs/preferences_dialog.py#L45

It should be possible to allow expansion. We need to be carefull that the windows doesn't resize to the size of the content like before and when all the content doesn't enter in the screen that scrollbar appear.  Otherwise we will break the dialog on small screen like in early 1.4 beta.

**Comment by jean-christophe-manciot** [comment]
It was possible in 1.3.13. The implementation of this basic feature should not depend on the size of the whole screen, should it?

**Comment by noplay** [comment]
It was break for small screen with 1.4 due to the addition to some options the windows start to be bigger than the smaller resolution supported. Due to this we have add scrollbar in some situations.

It should be possible to set a minimum size of the windows and ask Qt to not auto expanding the windows, and allow the user to resize. I didn't found how last time :(

**Comment by jean-christophe-manciot** [comment]
Works great in 1.4.2 :-)

**Comment by noplay** [comment]
;)

**Comment by noplay** [comment]
I forgot to close it.
