### ISSUE TITLE
Allow to use a remote server as the GNS3 VM

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#957]

**Comment by grossmj** [comment]
What if a user want to use multiple GNS3 VMs?

**Comment by noplay** [comment]
He can still use multiple remote server. But one of them will be aliased as the vm for topology.

**Comment by grossmj** [comment]
I've implemented it but I am not sure this is the best idea because this could break something...

![remote_gns3_vm](https://cloud.githubusercontent.com/assets/4752614/14057152/2b4b2c70-f2bd-11e5-8753-6e86de04cab4.png)

Should we support user/password and/or HTTPS for the server running in a local GNS3 VM? I would say no because the server is supposed to be isolated (answering only on the host only interface).

Finally, does user/password works for an HTTP server? (basic authentication?).

**Comment by noplay** [comment]
Perhaps we should just display a list box allowing you to choose a remote server as the VM and not duplicate the settings. And the VM will be just an alias to the remote server. 

I think we should also warn the user if the local server is not in the same subnet.

For the VM running in the GNS3 VM i agree about no HTTPS and no user and password. It's create a small risk that another user on the same host can access to the VM but it's not  designed for multiple user environnements. Protect it will increase a lot the complexity for the majority of the users. And we don't want user to change settings in the VM. We should also disallow people to change the port (I will fix https://github.com/GNS3/gns3-vm/issues/72).

For me the VM need to be use as provided if you want to change something install GNS3 on a server. Because we will not warranty that your config will be keep and compatible with our changes. And the VM need to be the same for 100% of the users  to simplify life.

**Comment by grossmj** [comment]
> We should also disallow people to change the port (I will fix GNS3/gns3-vm#72).

Problem is for users with existing settings. The port will be 8000 with no way to change that excepting editing the config file. However, we could hardcode the port.

> Perhaps we should just display a list box allowing you to choose a remote server as the VM and not duplicate the settings. And the VM will be just an alias to the remote server.

I was thinking about doing something like that but this is cumbersome because you have to add your remote, save/apply the settings and go back to GNS3 server VM to select the remote server.

**Comment by noplay** [comment]
The port could create an issue with ESXi users. We need to found a way to properly handle the server change case (password, port, ip...).  I propose #1144

Perhaps we should have a "add server" wizard that you can call from both page.
